### ISSUE TITLE
Can't get Google.Protobuf to work

### ISSUE THREAD

**Issue by Maufeat** [FeroxRev/Pokemon-Go-Rocket-API#1]
It says everytime that "the type or namespace name 'Protobuf' does not exists in the namespace 'Google'" but when I open NuGet Package Manager I clearly see "Google.Protobuf" and "Google.Protobuf.Tools" are installed.

**Comment by FeroxRev** [comment]
Can you hit restore nuget packages and make sure they are installed in both projects?

**Comment by Maufeat** [comment]
Compiles now. Is the Google Login working? I currently use the PTC but my console is blank. What do I have to change all? In Settings the "ClientSig" and "DeviceId" have to be changed? Thank you and sorry to bother you.

**Comment by FeroxRev** [comment]
Mitm the last /auth call from app to android.google.com. Check the request headers for the values that you need to update. It might take upto an hour before you actually see it.

**Comment by Maufeat** [comment]
Do not understand that one, do I have sniff the pokego http protocol for that? Not sure how to do that, would love to see an example or tutorial. Or maybe a login with email / pass or automate that

**Comment by FeroxRev** [comment]
Then i'd recommend the PTC login for now. Perhaps i'll add full google login later

**Comment by Maufeat** [comment]
Alright! Thank you, just have to wait until the PTC login server works / respond. :)
