### ISSUE TITLE
Might want to add a license.

### ISSUE THREAD

**Issue by jshield** [FeroxRev/Pokemon-Go-Rocket-API#10]
MIT, BSD, GPL what ever.

I know the project is already in a grey area from a licensing perspective, but still a good idea none the less.

**Comment by RazvanClint** [comment]
better not add any license or at least not MIT.  As i know, Riot (League of Legends) sued on EloBuddy (makers of a bot for lol) after they got MIT license because it is classified as cheating. Niantic can do the ame thing if this will have a mit license and they found out.

**Comment by jshield** [comment]
Can you link to either the court transcripts or a news article or even at the very least a forum/blog post backing up that claim. My google-fu can't find anything.

**Comment by FeroxRev** [comment]
Added GPL
