### ISSUE TITLE
Cant compile after last commit

### ISSUE THREAD

**Issue by azmanomer** [FeroxRev/Pokemon-Go-Rocket-API#100]
bca2166d72aaa9799c64965cc4f94748231283eb

**Comment by wardoUtil** [comment]
The problem for me is the Payloads.cs file.
It's not finding the Google namespace.

**Comment by chinnnathan** [comment]
newest update gives me 513 errors. Google namespace is my issue also

**Comment by fonix232** [comment]
The problem comes from moving the project files around without actually updating references.

Open PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj and replace all `..\..\` with `..\` - then it will build.

**Comment by chinnnathan** [comment]
Thank you, this makes it build

**Comment by FeroxRev** [comment]
Also fixed in master branch
