### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by FeroxRev** [FeroxRev/Pokemon-Go-Rocket-API#101]
Anyone got a chat environment we could use for better cooperation as @HelloKitty suggested?

**Comment by CoreTank** [comment]
discord i guess

**Comment by Martyn-Cleroux** [comment]
Discord could be used.

**Comment by azmanomer** [comment]
we can also use gitter like ; https://gitter.im/ZaneDubya/UltimaXNA?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by OranShuster** [comment]
Done
https://discord.gg/MbBv6

**Comment by FeroxRev** [comment]
Ok let's use discord! Awesome!
