### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by thorvak** [FeroxRev/Pokemon-Go-Rocket-API#102]
Now we need use all type pokeball with a good logic example if circle green/yellow use pokeball, if orange use ultraball if dont have ultraball try if other ball and clean inventory when full just take pokeball, egg, essence. Option for use egg chance and essence

**Comment by fonix232** [comment]
I don't think this should be part of the API. Maybe the Logic layer.

The API should really only contain the networking stack, requests and responses, whatnot, required to communicate with the Niantic servers.
