### ISSUE TITLE
how i test the now #Transfer pokemon #Evolve pokemon?

### ISSUE THREAD

**Issue by muyochy** [FeroxRev/Pokemon-Go-Rocket-API#104]
how i test the now #Transfer pokemon and 
#Evolve pokemon ? and if is automatic is not working

**Comment by h1pp0** [comment]
Look at the function TransferAllGivenPokemons and EvolveAllGivenPokemons in Program.cs

**Comment by muyochy** [comment]
thx but program.cs dont have that!

**Comment by azmanomer** [comment]
go login.cs line 107 and add this code;
await TransferDuplicatePokemon();

**Comment by muyochy** [comment]
azmanomer thx
yea dont work in line 107 but work in line 85
