### ISSUE TITLE
Extra Features

### ISSUE THREAD

**Issue by Crizpy** [FeroxRev/Pokemon-Go-Rocket-API#114]
First : Use Lucky Egg for double xp every 30 minutes .
Second : Remove automaticly anything besides Pokeballs so (Potions , Revives ... )
Third : Use special Pokeballs if Pokemon is harder to catch 
More to come.

**Comment by jshield** [comment]
All those features are currently listed on the wiki.

**Comment by PhoenixICE** [comment]
@jshield Whats the request for trash items, can't seem to figure out that

**Comment by jshield** [comment]
@PhoenixICE not currently implemented. I should clarify that those are requested features not currently implemented features.

**Comment by PhoenixICE** [comment]
Ahh so not all the requests have been ported yet, gotcha

**Comment by FeroxRev** [comment]
This is not a port, LOL. The amount of port repo's are crazy though
