### ISSUE TITLE
TransferDuplicatePokemon() is never executed in example programm

### ISSUE THREAD

**Issue by TheWebSmith** [FeroxRev/Pokemon-Go-Rocket-API#115]
In **logic.cs** starting from line 40 you have something like this:
`await _client.SetServer();`
`await RepeatAction(10, async () => await ExecuteFarmingPokestopsAndPokemons(_client));`
`await TransferDuplicatePokemon();`
The problem is that the third line is never executed. If I switch the last two, then Transfer[..] runs once.
I don't exactly know how this async()- and await-stufff works in C++, but if it is the same as in JavaScript, then there is something wrong with it.
As a temporary fix I removed `await TransferDuplicatePokemon();` and put `if (caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchSuccess) await TransferDuplicatePokemon();`. Now the check for douplicates runs after every successfull catch.

_Please don't kill me for that bad work, but I'm not a C++ dev ;)_

EDIT: Oh yeah, since this project is mainly an api and the bot is just an example on how to use these functions, my fix isn't such a good idea.

**Comment by jshield** [comment]
it will eventually perform the action after 10 repeats, if you look at the RepeatAction Method.
Also just a heads up this is a C# project not C++
Async/Await: https://msdn.microsoft.com/en-us/library/mt674882.aspx

**Comment by TheWebSmith** [comment]
Just for my understanding:

Everything is running in an infinite loop where `ExecuteFarmingPokestopsAndPokemons` is running for 10 different MapCells asynchromously. This task gets all Objects in this cell, moves from pokestop to pokestop while catching all the pokemon nearby after sleeping there for 15 seconds.

So technically it should execute `TransferDuplicatePokemon()` after 10 completed cellscans. That doesn't make sense to make. The amount of pokemon caught range from 0 to whatever. Until `TransferDuplicatePokemon` is executed, my inventory could already be full.

 It's way better to trigger it when `PokemonStorageCurrent == PokemonStorageMax` (or whatever it might be called), after every successfully caught pokemon (which might be overkill) or triggered every few minutes by a timer.

I've now caught over 80 pokemon and my inventory is full, so it is definitely taking too long to execute `TransferDuplicatePokemon` .

> Also just a heads up this is a C# project not C++
Yes I know, but there is hardly any difference. At least for me.

**Comment by jshield** [comment]
Yeah, a true bot would probably need the ability to rapidly update its objectives, then clear and queue new tasks based on local stimuli such as inventory being full. The example console app is really basic.

Once the fundamental logic for these actions are complete. I believe working on intelligence would be a good next step.
