### ISSUE TITLE
The transfer for duplicate doesn't work?

### ISSUE THREAD

**Issue by Antazia** [FeroxRev/Pokemon-Go-Rocket-API#116]

**Comment by Spegeli** [comment]
is that your fucking serious?

> TransferDuplicatePokemon() is never executed in example programm
#115 opened 27 minutes ago by TheWebSmith

**Comment by Antazia** [comment]
Yep but i'm a noob and i'm not English, I didn't really understood ^^

**Comment by jshield** [comment]
Meh, Duplicates happen. Of course it might help if there was a description of the issue.

Languages barriers exist, Google Translate exists for a reason.

**Comment by Antazia** [comment]
Yes I understand, but the problem is than I didn't understood how to do xd
