### ISSUE TITLE
GoogleRefreshToken Problem

### ISSUE THREAD

**Issue by bad1dea** [FeroxRev/Pokemon-Go-Rocket-API#118]
Anyone else encounter problem after 30-45mins, google auth accounts stop working. I have to manually edit the config files remove the GoogleRefreshToken key's and reauth to google.

If this is intended then please close/ignore.

**Comment by TheWebSmith** [comment]
I can confirm that.

**Comment by jshield** [comment]
The access token and refresh token could both have a very short life

**Comment by bad1dea** [comment]
From what I know about the OAuth, they shouldn't expire that soon. But I may be wrong. I've used it in the past for other web apps and generally only revoking access from the security page stops/invalidates them.

**Comment by bad1dea** [comment]
maybe,  adding access_type=offline to the following code will work -- testing now.
        public static async Task<TokenResponseModel> GetAccessToken(string refreshToken)
        {
            return await HttpClientHelper.PostFormEncodedAsync<TokenResponseModel>(OauthTokenEndpoint,
                new KeyValuePair<string, string>("client_id", ClientId),
                new KeyValuePair<string, string>("client_secret", ClientSecret),
                new KeyValuePair<string, string>("refresh_token", refreshToken),
                new KeyValuePair<string, string>("grant_type", "refresh_token"),
                new KeyValuePair<string, string>("scope", "openid email https://www.googleapis.com/auth/userinfo.email"));
        }

**Comment by jshield** [comment]
Yeah offline is required to get a refresh token, it is probably just returning an access token that probably has a very short life time.

**Comment by SoulDemon** [comment]
30 minutes lifetime...

**Comment by nowayrlz** [comment]
#123 I did your change and it worked, at least for me @bad1dea
