### ISSUE TITLE
SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing

### ISSUE THREAD

**Issue by Lasertrap00** [FeroxRev/Pokemon-Go-Rocket-API#12]
I am getting this error for the line: var serverResponse = await client.GetServer();

**Comment by FeroxRev** [comment]
You probably don't have the latest version. Pull please!

**Comment by Lasertrap00** [comment]
Ok will try

**Comment by Lasertrap00** [comment]
Is that normal?
 retry request https://pgorelease.nianticlabs.com/plfe/55/rpc

**Comment by FeroxRev** [comment]
Yes servers are more dead than alive

**Comment by Lasertrap00** [comment]
Ah ok good xD
