### ISSUE TITLE
Google Login without password

### ISSUE THREAD

**Issue by Artyfice** [FeroxRev/Pokemon-Go-Rocket-API#120]
When connecting to Pokémon Go, I've never been asked for my Google password. Is there a way to login without the password with this API?

**Comment by romeoDo** [comment]
This is one of the most idiotic question i have ever seen.

**Comment by Artyfice** [comment]
Sorry if my question is idiotic, I was just wondering how they did it.

**Comment by ongenoemd** [comment]
Google on "oauth" it will give you enough information to understand how.

**Comment by ryandailey100** [comment]
Delete your github account lol
