### ISSUE TITLE
Only using normal ball, not using Great Ball/Ultra Ball when catch pokemon

### ISSUE THREAD

**Issue by thaihuyhung** [FeroxRev/Pokemon-Go-Rocket-API#121]
Hi guys,

All the pokemon go away when there is no normal ball in my inventory.
I think it should use Great Balls, Ultra Balls, ...

Thanks for making this.

**Comment by jshield** [comment]
Duplicate of #66

**Comment by Spegeli** [comment]
A Pull Request is already open: https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/111
