### ISSUE TITLE
Empty Payload

### ISSUE THREAD

**Issue by PhoenixICE** [FeroxRev/Pokemon-Go-Rocket-API#122]
HttpClientExtensions.cs line22 - its possible for the server to return an empty payload so attempting to access index 0 causes an out of index error

**Comment by jshield** [comment]
Fix and submit a PR?

**Comment by PhoenixICE** [comment]
@FeroxRev this was closed without resolution?

**Comment by jshield** [comment]
Don't ignore it throw an exception or log it out.
