### ISSUE TITLE
Realistic movement - how often does app send updated location?

### ISSUE THREAD

**Issue by uvrt** [FeroxRev/Pokemon-Go-Rocket-API#129]
Currently we teleport from pokestop to pokestop. This is quite obvious behaviour for a bot. 
As the normal app is running, I suppose it periodically sends it location to the server. 

Does anybody know with what frequency? Sort of beaconing (e.g. every 30s)
If this behaviour would be mimicked, it would be much harder to detect that it is a bot.

**Comment by AssHole12** [comment]
Jap, just use Google Maps API and include ur pokestops for each region (each computer for it self), so you can go on streets, Niantic didnt build an Anti Cheat yet but trust me they will do things like checking which radio mast you are using, in Ingress they had this sick things

**Comment by jshield** [comment]
It doesn't you can send updates yourself with client.UpdatePlayerLocation though

**Comment by fonix232** [comment]
@AssHole12 Niantic did build an anti cheat system in - using any of these hacks as of now will result in a soft ban, meaning you can't catch any pokemon, and pokestops won't give you anything.
