### ISSUE TITLE
config file for settings

### ISSUE THREAD

**Issue by davidmann4** [FeroxRev/Pokemon-Go-Rocket-API#13]
I would preffer a .ini file:

[Settings]
DefaultLatitude = 45.030152
DefaultLongitude = -93.31931
username = 
password = 
useGoogleLogin = false
googleToken = 

if google token is null/empty it triggers login - when it is loaded it writes the token to ini

maybe we use this class? http://stackoverflow.com/questions/217902/reading-writing-an-ini-file

**Comment by davidmann4** [comment]
@FeroxRev @Maufeat

**Comment by FeroxRev** [comment]
Let's put it in the app.config

**Comment by davidmann4** [comment]
ok can we write it?

**Comment by davidmann4** [comment]
I am already thinking about a release version - people should be able to setup this thing without VS

**Comment by FeroxRev** [comment]
Go ahead. Thanks!

Let's focus on the code first and perhaps we can add a release later.

**Comment by Maufeat** [comment]
Ferox is right, people will flood this here and spam why things not working. Would like to avoid that, only costs time and nerves.

**Comment by Tobbo88** [comment]
Be a good idea but I've literally just started to download VS to get this ;) You should open a donations page tho.

**Comment by FeroxRev** [comment]
@davidmann4 Go ahead to create a settings class that fetches from app.config. Closing this issue and i'll wait for your PR .

**Comment by davidmann4** [comment]
will not do -  this solution is good
