### ISSUE TITLE
CatchPokemonResponse Pokemon ID is 0

### ISSUE THREAD

**Issue by Panthere** [FeroxRev/Pokemon-Go-Rocket-API#13]
Hey,

Immediately after capture I wish to get the last captured pokemon ID.
I do this right now by checking against certain attributes which can lead to it being wrong.

I am wondering whether this is a bug in the API or Pokemon Go...
Other people have also been able to replicate it.
From what I have seen there isn't a way to get the pokemon id on capture even from the encounter pokemondata instance.

**Comment by FeroxRev** [comment]
Fixed in latest version
