### ISSUE TITLE
Items exceeding 350 

### ISSUE THREAD

**Issue by brantje** [FeroxRev/Pokemon-Go-Rocket-API#137]
Had the bot running for a few hours, great job guy's!
However when i looked in my backpack, i had 443 / 350 items.
Not sure if niantic can detect it, but for sure this would increase the chance of a ban.
Currently at work, so can't fix it now, will look later.

**Comment by Spegeli** [comment]
This will not incrase the Bann Risko.
This happen when you Level to fast and you get new Items with every Level up.

**Comment by brantje** [comment]
Thanks for clarifying that. 
Maybe we should add it as a config option? Like `allowExceedBackPackSize`?
