### ISSUE TITLE
changing the way we do google auth

### ISSUE THREAD

**Issue by Zeromark30** [FeroxRev/Pokemon-Go-Rocket-API#138]
If you look at the python api for pogo, https://github.com/tejado/pgoapi. they use gpsoauth for python (https://github.com/simon-weber/gpsoauth) there is a C# port, https://github.com/vemacs/GPSOAuthSharp. this allows to skip the google.com/device thing and pretend to be an android app.

how the auth_google looks in python
`from __future__ import absolute_import

import logging

from pgoapi.auth import Auth
from gpsoauth import perform_master_login, perform_oauth

class AuthGoogle(Auth):'

    GOOGLE_LOGIN_ANDROID_ID = '9774d56d682e549c'
    GOOGLE_LOGIN_SERVICE= 'audience:server:client_id:848232511240-7so421jotr2609rmqakceuu1luuq0ptb.apps.googleusercontent.com'
    GOOGLE_LOGIN_APP = 'com.nianticlabs.pokemongo'
    GOOGLE_LOGIN_CLIENT_SIG = '321187995bc7cdc2b5fc91b11a96e2baa8602c62'

    def __init__(self):
        Auth.__init__(self)
        
        self._auth_provider = 'google'

    def login(self, username, password):
        self.log.info('Google login for: {}'.format(username))
        login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
        login = perform_oauth(username, login.get('Token', ''), self.GOOGLE_LOGIN_ANDROID_ID, self.GOOGLE_LOGIN_SERVICE, self.GOOGLE_LOGIN_APP,
            self.GOOGLE_LOGIN_CLIENT_SIG)
            
        self._auth_token = login.get('Auth')
        
        if self._auth_token is None:
            self.log.info('Google Login failed.')
            return False
        
        self._login = True
            
        self.log.info('Google Login successful.')
        self.log.debug('Google Session Token: %s', self._auth_token[:25])

        return True`

**Comment by FeroxRev** [comment]
Fixed the google auth by persisting the google refresh token properly. I don't see an issue in visiting the /device once. Another benefit is we dont need google username/pw in the setting file.
