### ISSUE TITLE
How to get Level/XP etc...?

### ISSUE THREAD

**Issue by Futfutfut** [FeroxRev/Pokemon-Go-Rocket-API#140]
Hey guys,

thats a very nice API but I have one question: How can i get current level or total xp of my account and stuff like that?

Example:
var inventory = await client.GetInventory();
var stats = inventory.InventoryDelta.InventoryItems[0].InventoryItemData.PlayerStats;

I know the things should be in .PlayerStats, but they are always null? Where can i get stats like these?

Thanks,
Futfutfut

**Comment by FeroxRev** [comment]
The players stats is in another InventoryItems index. You have to iterate through the list to find it iirc
