### ISSUE TITLE
Please ADMIN Help Me

### ISSUE THREAD

**Issue by tsebis** [FeroxRev/Pokemon-Go-Rocket-API#141]
Hey,

everytime when i try get some pokemon, appear "pokname" get away
i cannot gotcha none, please help me

**Comment by xDagon** [comment]
Not admin but you may check this:

You may be soft banned if you didn't put a close enough location in your setup file. Try to spin a pokestop, if you don't get items you are soft banned. If so, try to open, spin, then close a pokéstop for 10-50 times and it will unban you automatically.

**Comment by tsebis** [comment]
thx bro ill try

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)
