### ISSUE TITLE
Location Problem

### ISSUE THREAD

**Issue by Spack93** [FeroxRev/Pokemon-Go-Rocket-API#142]
if one of the coordinates have a - before it use the default location = soft ban^^

**Comment by pavelmoulisjr** [comment]
Testing 13 different locations, some with negative lat/long, some positive - no issues.

Pull new commits, make sure you start in the same location, make sure your lat/long is valid.

**Comment by Spack93** [comment]
in have add the same location ( the spot with 4 pokestops into the central park) and was on this coordinatew directly before i start the bot and get an instant softban.

**Comment by pavelmoulisjr** [comment]
Then there's no implication that it's an issue with negative values "-". Error probably on your end. 

Wait out soft-ban and try again, and remember to stay close to where you last started.

**Comment by pavelmoulisjr** [comment]
Furthermore, remember current Lat,Long is being used from UserSettings.settings, not App.config.
