### ISSUE TITLE
Feature Request: Discard items

### ISSUE THREAD

**Issue by Klizzer** [FeroxRev/Pokemon-Go-Rocket-API#143]
Now that the auto transfer is in place, I would like to see a discard all items of type X when there's more than Y in inventory, to avoid bag getting full.

I've been looking around but I can't seem to find any way to add this?

**Comment by jshield** [comment]
See wiki.

**Comment by Antazia** [comment]
Hi, please someone have the time to help me to setup the auto transfer? I am not English and i'm a shit in C++ ^^, I have teamviewver if someone can?
