### ISSUE TITLE
Move main repo to an organisation and add more maintainers?

### ISSUE THREAD

**Issue by jshield** [FeroxRev/Pokemon-Go-Rocket-API#144]
Good idea or no?

**Comment by FeroxRev** [comment]
Never used the organization. What's the benefit of it?

**Comment by jshield** [comment]
You can add people as maintainers of the repo, so they can be authorised to handle issues and pull requests.

**Comment by Spegeli** [comment]
I think only 1 should handle PR ;-)

**Comment by FeroxRev** [comment]
Yeah, i would love to hand out access for tracking issues/features and be in control of the main repo myself (at least for now)
