### ISSUE TITLE
Standing Still Option?

### ISSUE THREAD

**Issue by ShafferZee** [FeroxRev/Pokemon-Go-Rocket-API#146]
Would it be possible to add a flag in the setting to just stand still and collect what is within reach?
For populated locations like these?

![photoshop_2016-07-21 1469101992](https://cloud.githubusercontent.com/assets/1698537/17021796/e5dcf9fc-4f0f-11e6-8566-e5a0a44e6c46.png)

**Comment by FeroxRev** [comment]
Just keep calling the ExecuteCatchAllNearbyPokemonsmethod and not use the ExecuteFarmingPokestopsAndPokemons
