### ISSUE TITLE
Call GetMapObjects() but it never returns any information about pokestops or pokemons

### ISSUE THREAD

**Issue by taositkroopad** [FeroxRev/Pokemon-Go-Rocket-API#147]
Please help i've already call  GetMapObjects()

```
var mapObjects = await _client.Map.GetMapObjects();
var pokemons = mapObjects.Item1.MapCells.SelectMany(i => i.CatchablePokemons)
```

but it never returns any information about pokestops or pokemons
it returns 21 empty cells.

I read all issue but don't understand how to fix it.
Please help..

**Comment by Gabrola** [comment]
Use my fork #128, it should work fine

**Comment by taositkroopad** [comment]
Wow! Thanks so much.
It's totally work!
