### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Antazia** [FeroxRev/Pokemon-Go-Rocket-API#149]
Hi, sorry for my bad English and for this thread.
I will just ask if someone can give me his version because i don't know how to do in C++, I can pay a little bit...

Because I want Something to transfer unwanted pokemons and pokeball with CP choose....

Can someone help me? And sorry for this kiddy thread :/

**Comment by phr34k0** [comment]
It's C# not C++. Transfer is currently broken. Workable one is at http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/562773-c-bot-farming-pokestops-catching-pokemon.html

**Comment by FeroxRev** [comment]
Transfer is not broken

**Comment by Antazia** [comment]
I downloaded the original version but I don't work how it works, it never transfer !
Is that a beta with all news functions like hyperballs etc... ? Because idk how to did it
