### ISSUE TITLE
mscorlib issue?

### ISSUE THREAD

**Issue by pavelmoulisjr** [FeroxRev/Pokemon-Go-Rocket-API#15]
Having this issue over multiple commits. Seems to be bound to PTC login -- when PTC was commented out in Program.cs (prior to #11), Google login seemed to work fine.

'System.NullReferenceException'
![VS debug issue mscorlib](http://i.imgur.com/mmX6wOr.png)

**Comment by FeroxRev** [comment]
PTC Login is down

**Comment by pavelmoulisjr** [comment]
Ah, was my thought initially -- though curiously logging via app directly, I seem to have a higher chance of logging successfully. Assuming they just have a longer retry loop?

Btw, any clue of possibility of Charles on Bluestacks so I can fetch my ID & token? Their faq doesn't seem to deal with android emu's
