### ISSUE TITLE
Requirements for noobs

### ISSUE THREAD

**Issue by Ilmatarnyymi** [FeroxRev/Pokemon-Go-Rocket-API#150]
What does this require to run?

I dont need a spoon, just point me at the plate bruh.

**Comment by bad1dea** [comment]
visual studio 2015 (any addition)
open sln
select console app as startup project
edit app.config
hit build or build and run (f5 or ctrl+f5)

**Comment by Maufeat** [comment]
point to the plate? dude it's a program written in C#-Sharp, isn't that already the plate? ... bruh
