### ISSUE TITLE
Transfer pokemon does not occur.

### ISSUE THREAD

**Issue by lanarchyste** [FeroxRev/Pokemon-Go-Rocket-API#152]
Hello,

I use the application to farm near my home, but when I get a lot of pokemon, no transfer is made !
When I look at the code, the transfer method is implemented.

Is it possible that his is the following exception that the transfer is not done?
![exception](https://cloud.githubusercontent.com/assets/4154672/17022654/8195fd46-4f4f-11e6-82e1-859263e108cb.png)

Sorry for my english, i'm french :)

Thks

**Comment by kraizy** [comment]
#148

**Comment by lanarchyste** [comment]
Sorry for the double issue !
