### ISSUE TITLE
Unable to use PTC since 0feac8b

### ISSUE THREAD

**Issue by avoccados** [FeroxRev/Pokemon-Go-Rocket-API#157]
Since [this update](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/commit/0feac8b3e0eb16b471769d6ca6115765b9511166), I have not been able to use PTC.

I've tried:

```
 <setting name="AuthType" serializeAs="String">
        <value>Ptc</value>
      </setting>
```

```
 <setting name="AuthType" serializeAs="String">
        <value>PTC</value>
      </setting>
```

But when building in VS, it defaults to Google and asks me to do the /device process.

> Starting Execute on login server: Google

PTC login is working according to http://ispokemongodownornot.com/

**Comment by FeroxRev** [comment]
you need to edit UserSettings.settings and not the xml

**Comment by avoccados** [comment]
Still the same problem with PTC or Ptc

```
<Setting Name="AuthType" Type="System.String" Scope="User">
      <Value Profile="(Default)">Ptc</Value>
    </Setting>
```

Prompts google login

**Comment by FeroxRev** [comment]
Edit and then build/run from Vs. It works here..

**Comment by avoccados** [comment]
Steps I'm doing:

1) Fresh clone
2) Open userSettings.settings with VS and change Google to PTC (or Ptc), add username/pw, change lat/long
3) Open .sln and set console as startup

Still getting google login

**Comment by RyuIV** [comment]
Check whether the file is read-only or not. Alternatively open the userSettings.settings File in VS and edit the desired settings there, hit CTRL+S and F5.

**Comment by avoccados** [comment]
No luck, whether editing in Notepad or VS.. still brings up google auth.

Diff does show 

`<SettingsFile xmlns="http://schemas.microsoft.com/VisualStudio/2004/01/settings" CurrentProfile="(Default)" GeneratedClassNamespace="PokemonGo.RocketAPI.Console" GeneratedClassName="Settings">`

Changed to 

`<SettingsFile xmlns="http://schemas.microsoft.com/VisualStudio/2004/01/settings" CurrentProfile="(Default)" GeneratedClassNamespace="" GeneratedClassName="UserSettings">`

After editing with VS, not sure if relevant.  Otherwise, only other changes are auth/username/pw/loc
