### ISSUE TITLE
Transfer Duplication Max CP

### ISSUE THREAD

**Issue by Antazia** [FeroxRev/Pokemon-Go-Rocket-API#158]
Hi, I just wanna know, I download the official program (FeroxRev) without modifying anything, and i ask me the question, because I have 3 dragonite etc... I don't want to loose them, how can I do than it just transfer some pokemonIDS? thanks !

**Comment by RyuIV** [comment]
I had like 3 or 4 800CP+ Pidgeons and 3 of them got deleted because apparently they are dupes. 

You should restrict it to low CP or check if they are favorited in order to prevent loss of Pokémon that are actually wanted to stay. @FeroxRev

**Comment by Antazia** [comment]
Yes but I don't know anything with that... Can you give me your Skype or Something ?

**Comment by RyuIV** [comment]
It's not my project. Whether @FeroxRev fixes this or I might commit a pull-request when I'm home again, hoping it'll get commited to master.

**Comment by Antazia** [comment]
kk, yes but i don't care if a pidgeon 800 or 1000CP delete but with the original if i have 3 Dragonite will it delete or it just delete common pokemons?

**Comment by TheWebSmith** [comment]
Ignore favourites on dupe check sounds like a really good idea.

**Comment by Antazia** [comment]
Yeah !

**Comment by v4sp1** [comment]
just add a line on your transfert function, to check pokemon cp?

**Comment by Antazia** [comment]
Yep but I don't know how to do it... Can you give me your Skype or Something or say me how to do? Thanks and sorry i'm a shit..

**Comment by Iormangund** [comment]
`@@ -29,7 +29,7 @@ namespace PokemonGo.RocketAPI.Logic

            return myPokemon
                .GroupBy(p => p.PokemonId)
                .Where(x => x.Count() > 1)
                .Where(x => x.Count() > 3)
                .SelectMany(p => p.OrderByDescending(x => x.Cp).ThenBy(n => n.StaminaMax).Skip(1).ToList());
        }
`

**Comment by Antazia** [comment]
What is that?

**Comment by skupfer** [comment]
You should definitely add a function. I tried the script oob and it transfered a few very high CP pokemon (because it doesnt sort) ... stopped it immediately

**Comment by kerlos** [comment]
edit the SelectMany expressionl like this will ignore favorite to be tranfer

  return myPokemon
            .GroupBy(p => p.PokemonId)
            .Where(x => x.Count() > 1)
            .Where(x => x.Count() > 3)
            .SelectMany(p => p.Where(x=>x.Favorite == 0).OrderByDescending(x => x.Cp).ThenBy(n => n.StaminaMax).Skip(1).ToList());
    }

**Comment by skupfer** [comment]
Ah, yes... By ordering descending without any filter logic surely it goes from highest CP and leaves you the lowest. I am stupid today...

If I sort ascending it should work correctly, right? If I set skip(2) it should leave you these, right?

**Comment by Antazia** [comment]
Yes, but it will continue to transfer your duplicated pokemons, even your pokemons with 1500PC...
I can't find a way to make an unwanted list, another player already did it but it returns me to some fatals errors.
I will try again tonight if nobody find a way to make that, but it's just impossible for me -.-

**Comment by Spegeli** [comment]
I submitted a PR which ignores Favorite Pokemon: https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/176

Thx @kerlos

**Comment by skupfer** [comment]
@Antazia Ok, you are talking about duplicated ones. As far as the Logic goes it should return all but the highest one by PokemonId. But it transfered all and kept the lowest ones in my case. In my case I don't need an unwanted list, it can transfer every single duplicate as long as it keeps the one with the highest CP, which it doesn't ... Guess I am still not fully understanding this methods/functions

**Comment by kerlos** [comment]
from my above code if you want to keep the pokemon that has 1500+ cp then you can do like
` return pokemonList
                .GroupBy(p => p.PokemonId)
                .Where(x => x.Count() > 1)
                .SelectMany(p => p.Where(x=>x.Favorite == 0 && x.Cp < 1500).OrderByDescending(x => x.Cp).ThenBy(n => n.StaminaMax).Skip(1).ToList());`

**Comment by FeroxRev** [comment]
Create a PR for it, closing..
