### ISSUE TITLE
Show Pokemon

### ISSUE THREAD

**Issue by balloman** [FeroxRev/Pokemon-Go-Rocket-API#158]
What function lists the Pokemon a current user has?

**Comment by RickardPettersson** [comment]
client.Inventory.GetInventory()

**Comment by balloman** [comment]
I try that but get this error?

>    at BattleTime.Strategy.HandleApiFailure(RequestEnvelope request, ResponseEnvelope response) in C:\Users----\OneDrive\Documents\Programming\Pokemon-Go-Rocket-API-master\BattleTime\Strategy.cs:line 19
>    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\----\OneDrive\Documents\Programming\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 70
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in C:\Users\----\OneDrive\Documents\Programming\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 29
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at PokemonGo.RocketAPI.Rpc.Inventory.<GetInventory>d__4.MoveNext() in C:\Users-----\OneDrive\Documents\Programming\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Rpc\Inventory.cs:line 52
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at BattleTime.Exec.<MainAsync>d__2.MoveNext() in C:\Users----\OneDrive\Documents\Programming\Pokemon-Go-Rocket-API-master\BattleTime\Exec.cs:line 91

**Comment by dtabacaru** [comment]
I think your error is truncated a little so I can't tell what's happening (your error starts with the word 'at') but it seems like there may be a problem with your implementation of HandleApiFailure.

Can you paste it here? Maybe I can help then.

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)
