### ISSUE TITLE
Automatically Evolve Pokemon

### ISSUE THREAD

**Issue by theplaymate** [FeroxRev/Pokemon-Go-Rocket-API#160]
how do we get a list of pokemon that can be evolved? I tried to get it using inventory but failed. Any help would be appreciated.

**Comment by v4sp1** [comment]
+1

`var pokemons = _inventory.GetPokemons();
await EvolveAllGivenPokemons(pokemons);`

isn't working

**Comment by FeroxRev** [comment]
Feature added
