### ISSUE TITLE
Google Auth stacktrace

### ISSUE THREAD

**Issue by J-Saas** [FeroxRev/Pokemon-Go-Rocket-API#161]
After letting the latest version running for about an hour or so I'm getting this error:
http://i.imgur.com/LPGuhNh.png (Stacktrace only)
http://i.imgur.com/kDT18rJ.png (Full window)

It does continue on, however should you close the CLI and start it again you're served with a completely new set of errors (unfortunately I didn't make a screenshot of this, but will append once it happens again.)

Is this a known issue? Deleting the ..\PokemonGo.RocketAPI.Console\bin\Debug\ folder, re-building and authenticating with Google seems to fix the problem temporarily though.

**Comment by dreadylein** [comment]
Most likely related to some HTTP error response, please dump request and respond to narrow it down

**Comment by J-Saas** [comment]
I was away at a meeting. Let the bot run meanwhile, saw the errors popping up again.
Here is the error that comes up after re-starting the CLI: http://i.imgur.com/ZO1Jwrb.png

@dreadylein I'd be more than willing to do that.  Just print the response from response.Payload[0] in HttpClientExtensions.cs?

**Comment by FeroxRev** [comment]
You are on an old version. Closed
