### ISSUE TITLE
Using wrong location.

### ISSUE THREAD

**Issue by Newkz** [FeroxRev/Pokemon-Go-Rocket-API#164]
It uses the lat,lon from https://github.com/FeroxRev/Pokemon-Go-Rocket-API/blob/master/PokemonGo.RocketAPI.Console/UserSettings.settings

and not from App.config

Which is probably why people are getting softbanned. Cause they expect it to to use the config file, atleast I did.

**Comment by iargue** [comment]
I will confirm this, location is loading incorrectly.  We should add on line 38 of Logic.cs

`Logger.Write($"Latitude: {_clientSettings.DefaultLatitude}, Longitude: {_clientSettings.DefaultLongitude}", LogLevel.Info);`

To allow users to always see the location it is using before it runs (So they can abort and prevent a 3+ hour soft ban) May also be better to add a small delay before using the location so they can quit quick enough.

**Comment by Maufeat** [comment]
I still think rewriting the Settings to a settings.ini file would be the best...

**Comment by sooth** [comment]
settings.ini file would be wonderful, that way one can easily have multiple instances running (if so desired).
