### ISSUE TITLE
Transfer Pokemons?

### ISSUE THREAD

**Issue by pkiers** [FeroxRev/Pokemon-Go-Rocket-API#17]
Anyone already found out how to transfer pokemons? I did see TransferPokemonProto in the InventoryResponse.cs file.

**Comment by davidmann4** [comment]
:+1:  cool stuff!

**Comment by FeroxRev** [comment]
Planned to add tomorrow

**Comment by pkiers** [comment]
Awesome

**Comment by martin-podlubny** [comment]
@FeroxRev I only have a crude "forge all the Pidgeys" done so no PR, but to save you a bit of headache when you get around to doing it properly: 

Type of `PokemonProto.Id` at [InventoryResponse.proto line 156](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/blob/master/PokemonGo/RocketAPI/Proto/InventoryResponse.proto#L156) needs to be changed from `int32` to `fixed64`.. Otherwise all the pokemons returned from the inventory have incorrectly deserialized `PokemonProto.Id` with the value of 0. You need the actual value for trading and evolving :)

Also, awesome job 👏  Got me off the ground. Just wish I had a bit more time to contribute cleaned up code back to you :)

**Comment by thetemplar** [comment]
I changed the type to fixed64, but I still get id=0 somehow.
Did you manage to get a Transfer Request? I will do the rest to drop duplicate pokemons ;-)

**Comment by ArcticXWolf** [comment]
You have recompiled the protofiles to c# after doing the changes?

**Comment by thetemplar** [comment]
Ok,  now I feel stupid....  Thanks ;)

**Comment by martin-podlubny** [comment]
@ArcticXWolf yeah I did :) There might be an easier way, but I've done that with something along the lines of:
```
$ cd ./PokemonGo/RocketAPI/Proto 
$ protoc --proto_path=./ --csharp_out=../GeneratedCode --csharp_opt=base_namespace=PokemonGo.RocketAPI.GeneratedCode InventoryResponse.proto
```

**Comment by ArcticXWolf** [comment]
I created a pull request with updated proto files.

**Comment by thetemplar** [comment]
Yeah, it works now. Thanks.

But still I have not figured out how to transfer pokemon. Isnt the "RequestType" missing for that?

**Comment by martin-podlubny** [comment]
No PR, cuz rest of the code is messy, but I can help you @thetemplar with a method I added to the `PokemonGo.RocketAPI.client`:

```C#
public async Task<TransferPokemonOutProto> TransferPokemon(ulong pokemonId)
{
    var customRequest = new TransferPokemonProto
    {
        PokemonId = pokemonId
    };

    var releasePokemonRequest = RequestBuilder.GetRequest(_unknownAuth, _currentLat, _currentLng, 30,
        new Request.Types.Requests()
        {
            Type = (int)RequestType.RELEASE_POKEMON,
            Message = customRequest.ToByteString()
        });
    return
        await
            _httpClient.PostProto<Request, TransferPokemonOutProto>($"https://{_apiUrl}/rpc", releasePokemonRequest);
}
```

**Comment by ArcticXWolf** [comment]
martin, why not add this function as PR?

**Comment by blackms** [comment]
Definitely add this as PR.

**Comment by thetemplar** [comment]
Thanks, no duplicates anymore :)

`var inventory = await client.GetInventory();
                    var pokemons = inventory.Payload[0].Bag.Items.Select(i => i.Item?.Pokemon).Where(p => p != null && p?.PokemonType != InventoryResponse.Types.PokemonProto.Types.PokemonIds.PokemonUnset);

                    var dupes = pokemons.OrderBy(x => x.Cp).Select((x, i) => new { index = i, value = x })
                      .GroupBy(x => x.value.PokemonType)
                      .Where(x => x.Skip(1).Any());

                    for (int i = 0; i < dupes.Count(); i++)
                    {
                        for (int j = 0; j < dupes.ElementAt(i).Count() - 1; j++)
                        {
                            var pokemon = dupes.ElementAt(i).ElementAt(j).value;
                            var transfer = await client.TransferPokemon(pokemon.Id);
                            System.Console.WriteLine($"Transfer {pokemon.PokemonType} with {pokemon.Cp} CP");
                        }
                    }`

**Comment by FeroxRev** [comment]
Could you add a PR for the transfer code? :)

**Comment by martin-podlubny** [comment]
Will do, approximately 1 hour from now :) 

I did the lazy/quick thing of not cloning and committing my work, but just downloading the repo ZIP package and hacking what I needed on top of that :D 

Will do it properly in a bit and submit a PR, adding even few more methods that I have done ready that you could actually use. Like `MeatGrindAllButOneStrongest(PokemonIds.V0016PokemonPidgey)` and `EvolveAsManyAsPossible(PokemonIds.V0016PokemonPidgey)`

**Comment by martin-podlubny** [comment]
Feel free to assign me to the issue

**Comment by martin-podlubny** [comment]
With pokemon transfer I got the bot to do:

1) walk (not teleport) from stop to stop, catch all pokemon while doing so for all stops discovered from the initial location
2) meat grind all-but-strongest shitty/common farmed pokemon
3) walk (not teleport) to the starting location
4) repeat

**Comment by skupfer** [comment]
A walk / not teleport function would be great! Cant wait for your PR :)

**Comment by martin-podlubny** [comment]
@skupfer I pretty much just copy/pasted code from the yet-unmerged https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/19 :D Guys at that PR are properly working on that kind of stuff so we're waiting on their PR :)

**Comment by FeroxRev** [comment]
Ok this is implemented!
