### ISSUE TITLE
how to stop evolove the pokemons which is more than 12 candies?

### ISSUE THREAD

**Issue by fee622** [FeroxRev/Pokemon-Go-Rocket-API#17]
how to stop evolove the pokemons which is more than 12 candies? 
thanks

**Comment by reallemon** [comment]
`if (familyCandy.Candy - pokemonCandyNeededAlready > settings.CandyToEvolve && ( pokemon.PokemonId == PokemonId.Rattata ||
                                                                                                pokemon.PokemonId == PokemonId.Pidgey || pokemon.PokemonId == PokemonId.Pidgeotto || 
                                                                                                pokemon.PokemonId == PokemonId.Caterpie || pokemon.PokemonId == PokemonId.Metapod ||
                                                                                                pokemon.PokemonId == PokemonId.Weedle || pokemon.PokemonId == PokemonId.Kakuna )
                   )`

Insert this code at line 108 in the inventory.cs file under Pokemongo.RocketAPI.Logic. You can replace those names with the names of any pokemon you want, and only those named pokemon will be evolved.

**Comment by FeroxRev** [comment]
Logic moved out of this repo
