### ISSUE TITLE
Adding support for GPX (Google Routes)

### ISSUE THREAD

**Issue by pkiers** [FeroxRev/Pokemon-Go-Rocket-API#18]
Just so you know, I started working on import of GPX file. So you can plan out a route on Google Maps and export that to GPX file. That way you are just walking around catching pokimons instead of fixed position.

**Comment by ArcticXWolf** [comment]
Nice, great idea!

**Comment by basst85** [comment]
Can you also implement support for .kml or .kmz files?
You can make a path in Google Earh and save it as .kml.

**Comment by FeroxRev** [comment]
Cool idea, adding to wiki and closing this issue
