### ISSUE TITLE
Not an issue but just to see interest

### ISSUE THREAD

**Issue by spikeone83** [FeroxRev/Pokemon-Go-Rocket-API#192]
![liveview](https://cloud.githubusercontent.com/assets/20557688/17031857/544f86fa-4f44-11e6-98aa-d149acc6f60b.png)

checking interest in me continuing this?

self explanatory for now, will be re adding my code to show google map with position and items

**Comment by dreadylein** [comment]
Not an issue, best ask at the discord channel for feedback :)
