### ISSUE TITLE
Google Protobuf error

### ISSUE THREAD

**Issue by Meeplez** [FeroxRev/Pokemon-Go-Rocket-API#195]
Not compiling as of 7/21/2016
Missing Google Protobuf error.

FIX#----!

Remove google protobuff, and re-add Packages/Google.Protobuf.3.0.0-beta3
in:  PokemonGo.RocketAPI.Logic

**Comment by dreadylein** [comment]
Can someone Confirme this ?

**Comment by Thunderkill** [comment]
I just built the solution and it worked for me.

Not 100% sure if that fixed it, need someone to confirm

**Comment by dreadylein** [comment]
Seems fine atm, i will close this for now, if someone else is reporting this problem i will reopen and merge the issue.

**Comment by Th3C0D3R** [comment]
where i finde the Packages/Google.Protobuf.3.0.0-beta3 :O
