### ISSUE TITLE
Easy customization

### ISSUE THREAD

**Issue by GamespikeYT** [FeroxRev/Pokemon-Go-Rocket-API#196]
is it possible to get more options in the app.config file lik for instance the evolve and transefer feature? There was another post from someone who edited you version of the API 
[Pokemon-Go-Rocket-API-master (6).zip](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/files/376607/Pokemon-Go-Rocket-API-master.6.zip)
here we can choose which modes we use for transfer etc

thanks for consideration

**Comment by dreadylein** [comment]
Not api related, feel free to submit a PR for logic improvments :)
