### ISSUE TITLE
DeployedFortId always return 0

### ISSUE THREAD

**Issue by pdtan** [FeroxRev/Pokemon-Go-Rocket-API#2]
Pokemon is in gym but DeployedFortId = 0

**Comment by FeroxRev** [comment]
Please check if fixed in new version. I don't have any pokemon in gyms

**Comment by pdtan** [comment]
Payloads.cs
`case 64:
                        {
                            DeployedFortId = input.ReadInt32();
                            break;
                        }`
I checked, no case 64 here, only 66 appeared when pokemon is in gym.
How to change it to 66? I tried, but it's return SkipLastField error

**Comment by FeroxRev** [comment]
So what's the field id?

**Comment by pdtan** [comment]
DeployedFortId in PokemonData

**Comment by FeroxRev** [comment]
The integer?

**Comment by pdtan** [comment]
yes. It's Integer field
http://pastebin.com/ja0Qwc6B
I use System.Console.WriteLine(tag); to display all tag case, and tag 66 appeared when pokemon is in gym

**Comment by FeroxRev** [comment]
Im talking about the proto fieldnumber, not sure what youre looking at in the generated code

**Comment by pdtan** [comment]
proto fieldnumber is 8

**Comment by pdtan** [comment]
Output of tag case with my pokemon list, one is in gym now (66 displayed)
http://pastebin.com/mTA5BF2z

**Comment by FeroxRev** [comment]
Woops, please try again

**Comment by pdtan** [comment]
Tried but it's still 0
here dump tag for my pokemon list, one of Vaporeons' in gym
http://pastebin.com/6zSj79BQ

**Comment by FeroxRev** [comment]
Please dump the response with charles, decode protobuf and put it here please

**Comment by pdtan** [comment]
I don't know to do that. Hope other can fix this.
