### ISSUE TITLE
Added another way to login with Google. (Messed up my fork)

### ISSUE THREAD

**Issue by Maufeat** [FeroxRev/Pokemon-Go-Rocket-API#2]
Hey,

I took the few hours to add a way to login with Google, well it is a little bit of a "work around", it requires you to visit "google.com/devices" which is copied from the java API but that is a way it works for me.

I messed up my commit, hope you can still implement that method.

https://github.com/Maufeat/Pokemon-Go-Rocket-API/commit/7d88c9348213c7442b0d1b89ee77ed9c22681dec

**Comment by ardaozkal** [comment]
would you mind if I sent that? I fixed it.

**Comment by FeroxRev** [comment]
Tomorrow i have time to look into adding/merging google login completely.

**Comment by davidmann4** [comment]
I made a PR https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/9

hope you do not mind

**Comment by Maufeat** [comment]
Well, this got merged. So I close this.
