### ISSUE TITLE
config for google account ?

### ISSUE THREAD

**Issue by muyochy** [FeroxRev/Pokemon-Go-Rocket-API#20]
hi i use my ptc and work relly good
but i try with my google account and dint work help thx

**Comment by ArcticXWolf** [comment]
With the latest version just enter your credentials in Settings.cs
You do not need to modify anything in Program.cs!

**Comment by youngsemicolon** [comment]
@ArcticXWolf Can you show your Settings.cs ? I cannot get it working

**Comment by NoiseControllers** [comment]
change "true" by "false" in settings.cs

public const bool UsePTC = true; //false to use gmail.
I have not tried it xD

**Comment by muyochy** [comment]
i put the device id , email, clientsig and token  nothing do error when i try to start

**Comment by jakesteele** [comment]
How do you guys get the token? I tried the charles proxy from my shield but it never has a request from android.google.com and none of the headers seem to contain a device id and token.

**Comment by muyochy** [comment]
you install the ssl certificate is not the same from the normal for get the info and you need ative the ssl proxy  in charles to

**Comment by FeroxRev** [comment]
Closing because not an actual issue of the library
