### ISSUE TITLE
Grinder Skips over half the pokemon

### ISSUE THREAD

**Issue by Guthans** [FeroxRev/Pokemon-Go-Rocket-API#200]
Hello, Theirs an issue with the grinder when grinding it doesn't even do all the pokemons that needs to be grinds it maybe does one or two.

My solution was just increasing the delay from 3000, 5000-7000 and it works perfectly.

**Comment by dreadylein** [comment]
Can you explain what exactly was the Problem ?

**Comment by Guthans** [comment]
When the meat grinder loops through the pokermon to grind it would only do a pidgey then skip over the other pokemons it supposed to grind. So I increased the delay and it now loops over all of them for me.

This is how it looks for me when its working correctly with the delay.
![d1424019984fc2b99ef1b574b3ed32c6](https://cloud.githubusercontent.com/assets/8345926/17032933/afe01f20-4f49-11e6-8ac1-0cb5949295ce.gif)

**Comment by Iormangund** [comment]
I think you opened an issue on the wrong repo. Necro's fork uses the grinder stuff, Ferox's says 'Transfer' and nothing about meat grinder.

**Comment by dreadylein** [comment]
Wrong repo .. :P , closed
