### ISSUE TITLE
POGOProtos could not be found.

### ISSUE THREAD

**Issue by mpah** [FeroxRev/Pokemon-Go-Rocket-API#22]
For some reason my references can not find POGOprotos since I pulled today. Where exactly are those located now?

**Comment by ritl-de** [comment]
Nuget Package -> google

right click on the Project -> Manage Nuget Package -> click on restore

**Comment by mpah** [comment]
That's what I did, which worked for all packages except for POGOProtos
![image](https://cloud.githubusercontent.com/assets/15245583/17106571/1f51790e-528c-11e6-80d7-b53a60f92bcf.png)

**Comment by mpah** [comment]
Hmm switching from 1.2 to 1.1 and back to 1.1 worked. I guess for some reason nuget assumed it was installed when it wasnt. Same thing happened when I downloaded a fresh repo so I wonder if it's an issue on my end only.

**Comment by ritl-de** [comment]
downloading fresh repo + nuget restore  fix the POGOProto missing

**Comment by mpah** [comment]
Weird so its definitely on my end then. Thanks for your help!
