### ISSUE TITLE
Prioritize Evolution of Level 1 Pokemon

### ISSUE THREAD

**Issue by theplaymate** [FeroxRev/Pokemon-Go-Rocket-API#220]
Right now basic pokemon are give priority over level 1 pokemon. For example if we catch a lot of poliwags, it will only evolve poliwags which will become polywhirls. And as 25 candy is needed to evolve a poliwag, there will never be enough candy to evolve a polywhirl. Kindly look into it if you have time please. Thank you

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
