### ISSUE TITLE
Losing pokemon

### ISSUE THREAD

**Issue by Serellyn** [FeroxRev/Pokemon-Go-Rocket-API#223]
I've published the .console solution and started the application. Then it asked me to give google permission to use the computer I'm on, so I did and then it stated that it was transferring Pokemon. I thought maybe 2 seconds about it and killed the application. Now after restarting Pokemon Go on my Android phone it appears that ~20 of my Pokemon have been removed. How is this possible, where are my Pokemon gone?

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments

They were discarded.
