### ISSUE TITLE
Enum CHARMENDER

### ISSUE THREAD

**Issue by navidemad** [FeroxRev/Pokemon-Go-Rocket-API#224]
> I don't know if it is a issue from API side or from your side.

I guess you should replace ~~{CHARMENDER}~~ by **{CHARMANDER}**

[Proto/AllEnum.proto](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/blob/0307c246928b72d5fcbdd3ece051ed7bd27a75e9/PokemonGo.RocketAPI/Proto/AllEnum.proto#L419):
```
enum PokemonId {
    ...
    CHARMENDER = 4;
    ...
}
```

[GeneratedCode/AllEnum.cs](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/blob/bca2166d72aaa9799c64965cc4f94748231283eb/PokemonGo.RocketAPI/GeneratedCode/AllEnum.cs#L758):
```
public enum PokemonId {
    ...
    [pbr::OriginalName("CHARMENDER")] Charmender = 4,
    ...
}
```

**Comment by navidemad** [comment]
#232

**Comment by FeroxRev** [comment]
The proto files are out-generated with the wrong name. No use in fixing it as it will get overridden again
