### ISSUE TITLE
Error When trying to Build

### ISSUE THREAD

**Issue by Velorianvx77** [FeroxRev/Pokemon-Go-Rocket-API#229]
I anyone having an issue when trying to Build that there is an error as follows: Severity    Code    Description    Project    File    Line    Suppression State
Error    CS0006    Metadata file 'E:\Helpful Software\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI.Logic\bin\Debug\PokemonGo.RocketAPI.Logic.dll' could not be found    PokemonGo.RocketAPI.Console    E:\Helpful Software\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI.Console\CSC    1    Active

**Comment by Meeplez** [comment]
Yeah i posted this earlier and it didn't work,  You have to remove Google.Protobuff then re-add it from the branch.

**Comment by Velorianvx77** [comment]
Oh ok.  Thank you!
