### ISSUE TITLE
improve README

### ISSUE THREAD

**Issue by youngsemicolon** [FeroxRev/Pokemon-Go-Rocket-API#23]
The README is very unclear. I guess a lot of people here dont do c# so this deserve a more in-depth explanation. _This will also avoid spams here_

**Comment by MrUnreal** [comment]
What do you mean unclear ? The project is currently literally download-compile-run. If you dont do c# you cant help with the development, thats the opposite of what any dev making his project on github wants.

**Comment by OranShuster** [comment]
there is no prompt for username/password in the console. it is expected to be written in the settings.cs file >not in readme
not alot of explanation how to get the device id
