### ISSUE TITLE
Wrong documentation example

### ISSUE THREAD

**Issue by alecamaracm** [FeroxRev/Pokemon-Go-Rocket-API#237]
I think the use example in README.md is outdated:

`var client = new Client(Settings.DefaultLatitude, Settings.DefaultLongitude);

await client.LoginPtc("FeroxRev", "Sekret");
var serverResponse = await client.GetServer();
var profile = await client.GetProfile();
var settings = await client.GetSettings();
var mapObjects = await client.GetMapObjects();
var inventory = await client.GetInventory();

await ExecuteFarmingPokestops(client);
await ExecuteCatchAllNearbyPokemons(client);`

In current version, client class can only be initialized with an ISettings param instead of latitude and longitude ones.

**Comment by FeroxRev** [comment]
Updated
