### ISSUE TITLE
Can  you please add items drop and drop pokemons under x CP? :P would be great!

### ISSUE THREAD

**Issue by vol0dya** [FeroxRev/Pokemon-Go-Rocket-API#24]
Also auto evolution will be apreciated

**Comment by Esummoner** [comment]
Transfering pokemons under x CP could better be changed to keep the highest cp 1-x number of pokemon and transfer all lower ones.

**Comment by martinp-rg** [comment]
Relevant PRs that do similar or needed stuff are 

- [Add Client.TransferPokemon(...) and Client.EvolvePokemon(...) #50](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/50)
- [add Program.TransferAllGivenPokemons(...) and Program.EvolveAllGivenPokemons(...) #51](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/51)
- [add Program.TransferAllButStrongestUnwantedPokemon(...) #53](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/53)

**Comment by jakesteele** [comment]
this isnt great, but it works and its a ruff sketch:

`private static async Task RemoveLowCpMons(Client client)
        {
            var inventory = await client.GetInventory();
            var pokemons = inventory.Payload[0].Bag.Items.Select(i => i.Item?.Pokemon).Where(p => p != null && p?.PokemonId != InventoryResponse.Types.PokemonProto.Types.PokemonIds.PokemonUnset);
            foreach (var p in pokemons)
            {
                if (p.Cp <= 210)
                {
                    var r = await client.ReleasePokemon(p.Id);
                }
            }
        }`
`public async Task<ReleasePokemonResponse> ReleasePokemon(ulong pokemonId)
        {
            var customRequest = new Request.Types.ReleasePokemonRequest()
            {
                PokemonId = pokemonId
            };

            var releasePokemonRequest = RequestBuilder.GetRequest(_unknownAuth, _currentLat, _currentLng, 30,
                new Request.Types.Requests()
                {
                    Type = (int)RequestType.RELEASE_POKEMON,
                    Message = customRequest.ToByteString()
                });
            return
                await
                    _httpClient.PostProto<Request, ReleasePokemonResponse>($"https://{_apiUrl}/rpc", releasePokemonRequest);
        }`

`syntax = "proto3";

package PokemonGo.RocketAPI.GeneratedCode;

message ReleasePokemonResponse {
   Result result = 1;
   int32 candy_awarded = 2;

  enum Result {
    UNSET = 0;
    SUCCESS = 1;
    POKEMON_DEPLOYED = 2;
    FAILED = 3;
    ERROR_POKEMON_IS_EGG = 4;
  }
}`

--- Add the below to the Request.proto
`syntax = "proto3";
package PokemonGo.RocketAPI.GeneratedCode;
message ReleasePokemonRequest {
   fixed64 pokemon_id = 1;
}`


regenerate the protos with the beta 4 and 
protoc --csharp_out=. {name}.proto

and it will work. its not the best way to do it but it works and is fairly fast. just add the code on a timer or after you catch x pokemon or w/e you want. change the value from 210 to the cut off cp
