### ISSUE TITLE
GoogleLogin.GetAccessToken returns Bad Request

### ISSUE THREAD

**Issue by mpah** [FeroxRev/Pokemon-Go-Rocket-API#24]
GoogleLogin.GetAccessToken returns 400 'Bad Request'.

IDs blacked out for privacy:
![image](https://cloud.githubusercontent.com/assets/15245583/17109335/e529d0d0-5297-11e6-8d3d-f4bd6315ea12.png)

**Comment by FeroxRev** [comment]
This probably means you supplied an invalid refresh token. Perhaps a problem in your persisting layer?

**Comment by mpah** [comment]
Thanks it works now
