### ISSUE TITLE
Failed to transfer pokemon

### ISSUE THREAD

**Issue by Murumuru** [FeroxRev/Pokemon-Go-Rocket-API#240]
Pokemon transfer fails when .ReleasePokemonOutProto.Status == 2. It means pokemon is busy in gym. There should be some handle for this situation.

**Comment by FeroxRev** [comment]
Fixed https://github.com/FeroxRev/Pokemon-Go-Rocket-API/commit/f0e01385d10e37c69eb134cf5682a8ee96fd2a45
