### ISSUE TITLE
NullReferenceException trying to log in using PTC

### ISSUE THREAD

**Issue by eslindsey** [FeroxRev/Pokemon-Go-Rocket-API#241]
When trying to log in using my PTC account, I get a `NullReferenceException` that I have traced to [line 44 of PtcLogin.cs](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/blob/f0e01385d10e37c69eb134cf5682a8ee96fd2a45/PokemonGo.RocketAPI/Login/PtcLogin.cs#L44). Specifically, `loginResp.Headers.Location` is null, and thus trying to reference `Query` causes a `NullReferenceException`.

**Comment by PhoenixICE** [comment]
Pretty sure this is because you are using an old commit

**Comment by FeroxRev** [comment]
Thank you! I just found another issue related to this. fixed in latest commit
