### ISSUE TITLE
Additional Parameters for CatchPokemon

### ISSUE THREAD

**Issue by Lizzaran** [FeroxRev/Pokemon-Go-Rocket-API#245]
Additional parameters for CatchPokemon:

- HitPokemon
- NormalizedReticleSize
- SpinModifier
- NormalizedHitPosition 

so we are able to randomize the values to not throw always a perfect ball.

**Comment by Maufeat** [comment]
B..b..but that extra XP D:

**Comment by berbb** [comment]
+1

**Comment by FeroxRev** [comment]
Submit a PR and i accept it!
