### ISSUE TITLE
Bot freeze

### ISSUE THREAD

**Issue by Fedorus** [FeroxRev/Pokemon-Go-Rocket-API#248]
Sometimes console is just freezing until U push some button. 
it`s strange because there is no Console.Read or something
[Picture](http://s8.hostingkartinok.com/uploads/images/2016/07/3a1812371ad75df84aae37fb5473e95c.jpg
)
As you can see there is time-gap between  1:48  and 1:51 if I wouldn`t push a button it would be still waiting. After pushing button will come 1 or 2 "old messages" and then it continues to work.

**Comment by depl0y** [comment]
I am pretty sure this is just a "oops, I clicked my mouse within the console and selected some text" thing. This pauses the console and resumes it when you press a key.

**Comment by FeroxRev** [comment]
Exactly
