### ISSUE TITLE
Pokemon catched and not

### ISSUE THREAD

**Issue by Fedorus** [FeroxRev/Pokemon-Go-Rocket-API#249]
Sometimes program prints that: "pokemon caught" and right after that: "pokemon  got away". CP is the same so I suppose that it`s the same pokemon.
Plus after that, there is an error that pokemon can`t be grinded.

**Comment by Meeplez** [comment]
I think this relates to the Execute.Wait() fix. The application does actually respond and reacts Successfully with Pokemon GO. The console output will not report this however.

**Comment by FeroxRev** [comment]
"Grinded"

You are on another version my friend
