### ISSUE TITLE
Bot try to transfer Pokemon wich are in a Arena

### ISSUE THREAD

**Issue by neorm** [FeroxRev/Pokemon-Go-Rocket-API#253]
The Bot try to transfer Pokemon wich are in a Arena, and keeps trying it.

**Comment by navidemad** [comment]
Already implemented I guess.
[Source of following code:](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/blob/master/PokemonGo.RocketAPI.Logic/Inventory.cs#L90)
```
//Don't evolve pokemon in gyms
var pokemonList = myPokemon.Where(p => p.DeployedFortId == 0).ToList();
```
