### ISSUE TITLE
Feature Request: Favoriting a pokemon stops it from being transfered

### ISSUE THREAD

**Issue by Zeromark30** [FeroxRev/Pokemon-Go-Rocket-API#257]
I don't know if favoriting a pokemon is transmitted to and from the server or not but if we did favorite a pokemon(the star icon) make it not transfer regardless of the other criteria it may fit.

That or don't transfer pokemon with a combined IV score above 90% (tech 91% for 41/45)
IV is calculated from adding individual_attack, individual_defense and individual_stamina. so the pokemon below would have an IV of 16 and should be transferred because he is only 35.5% perfect and has less potential than other pokemons.
`{   'inventory_item_data': {   'pokemon_data': {   'captured_cell_id': ,
                                                                                                                                           'cp': 42,
                                                                                                                                           'creation_time_ms': 1467896285015L,
                                                                                                                                           'height_m': 0.27494046092033386,
                                                                                                                                           'id': 2609019257151675480L,
                                                                                                                                           'individual_attack': 11,
                                                                                                                                           'individual_defense': 4,
                                                                                                                                           'individual_stamina': 1,
                                                                                                                                           'move_1': 211,
                                                                                                                                           'move_2': 45,
                                                                                                                                           'pokeball': 1,
                                                                                                                                           'pokemon_id': 21,
                                                                                                                                           'stamina': 17,
                                                                                                                                           'stamina_max': 17,
                                                                                                                                           'weight_kg': 1.6279398202896118}}},`

**Comment by Jagermeister56** [comment]
I think that would be an awesome addition. I lost my second gyarados :'(

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
