### ISSUE TITLE
How to disable auto evolve Pokemon?

### ISSUE THREAD

**Issue by hotfilehd** [FeroxRev/Pokemon-Go-Rocket-API#258]

**Comment by Fedorus** [comment]
Search line:
await EvolveAllPokemonWithEnoughCandy();

And recommend you to search this one: (2 times)
 //await RecycleItems();

**Comment by hotfilehd** [comment]
How to disable Please!
Sorry because im dummy about visual studio!

**Comment by Fedorus** [comment]
Add // before the line

**Comment by joshuroar** [comment]
If you comment out RecycleItems, the bot will stop working after a little while due to the bag filling up. If you don't want to have to babysit the bot, RecycleItems is a decent compromise until we get a smarter item management system.

**Comment by Fedorus** [comment]
It recycles almost all items, no priorities or something, it`s better to keep items until you do something better. it even throws away pokeballs...

**Comment by hotfilehd** [comment]
Thanks you so much! 
Fedorus!

**Comment by Merudo** [comment]
Why is this not an option in usersettings.settings ?!

**Comment by joshuroar** [comment]
Right now the tradeoff is that you get a bot that works without needing to be reset. Better logic for handling items is possible, but again, the bot *will* stop working entirely after some time without item management.

**Comment by Meeplez** [comment]
This should also be added to XML, preference.

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
