### ISSUE TITLE
loginResp.Headers.Location = null

### ISSUE THREAD

**Issue by jakesteele** [FeroxRev/Pokemon-Go-Rocket-API#26]
Not finding the location and is unable then to find the ticket id. What does the ticket id look like?

loginResp.Headers
{X-Px: nc h0-s204.p11-sjc ( h0-s1008.p10-jfk), nc h0-s1008.p10-jfk ( origin>CONN)
Pragma: no-cache
Access-Control-Allow-Origin: https://www.pokemon.com
Access-Control-Allow-Credentials: true
Connection: keep-alive
Cache-Control: no-store
Date: Tue, 19 Jul 2016 22:32:01 GMT
Server: PWS/8.1.38
}
    AcceptRanges: {}
    Age: null
    CacheControl: {no-store}
    Connection: {keep-alive}
    ConnectionClose: null
    Date: {7/19/2016 10:32:01 PM +00:00}
    ETag: null
    **Location: null**
    Pragma: {no-cache}
    ProxyAuthenticate: {}
    RetryAfter: null
    Server: {PWS/8.1.38}
    Trailer: {}
    TransferEncoding: {}
    TransferEncodingChunked: null
    Upgrade: {}
    Vary: {}
    Via: {}
    Warning: {}
    WwwAuthenticate: {}
    acceptRanges: {}
    generalHeaders: {System.Net.Http.Headers.HttpGeneralHeaders}
    headerStore: Count = 8
    invalidHeaders (System.Net.Http.Headers.HttpHeaders): Count = 11
    parserStore (System.Net.Http.Headers.HttpHeaders): Count = 18
    proxyAuthenticate: {}
    server: {PWS/8.1.38}
    vary: {}
    wwwAuthenticate: {}
    Results View: Expanding the Results View will enumerate the IEnumerable

**Comment by FeroxRev** [comment]
PTC Server is down
