### ISSUE TITLE
Improved automatic evolutions - whitelists, other criteria

### ISSUE THREAD

**Issue by joshuroar** [FeroxRev/Pokemon-Go-Rocket-API#260]
Case example issues:

1) I've had some pigeotto and kakuna get autoevolved, which is pointless and ate up a bunch of candies. Tons of lost XP. All the low tier pokemon with three evolutions need to be autoevolved only from their lowest tier form.

2a) High tier pokemon need to be selected with more care. I imagine people will be pretty sad if they have 5 dratinis, 125 candies, and they all get evolved to dragonairs...

2b) I had an eevee get autoevolved. This isn't a huge deal, but I don't just want to evolve arbitrary eevees, even if we use the highest CP eevee I found so far. It needs to be an eevee with high stats (IVs) and reasonable CP. Otherwise I would prefer to turn it into candy for a future eevee. This strategy makes sense for high-tier pokemon that are relatively easy to find. I imagine I will be pretty sad after getting 400 magikarp candies and then evolving the next magikarp I find, even if it's bad. It would make sense to go through at least a few more to find one with decent stats. I'd argue that due to the grind structure, we should be willing to hunt down 100 more magikarps or so to find one in the top 1%.

----

If this tech isn't implemented, should we be autoevolving at all? In the meantime, just let us do it manually, and whitelist pidgey, weedle, caterpie, zubat. Don't whitelist kakuna or other 2nd tier forms.

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
