### ISSUE TITLE
Improve autoTransfer

### ISSUE THREAD

**Issue by Fedorus** [FeroxRev/Pokemon-Go-Rocket-API#261]
If I have 5 pokemons 1000-1100 I don`t wanna transfer them into cookies especially if I have plenty of space in the bag.

**Comment by Meeplez** [comment]
I think its been said before, this needs to be exported to xml or some type of preference file, I don't think its there yet, but it should eventually.

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
