### ISSUE TITLE
feature request : xp boost with 12 candies pokemon evolve

### ISSUE THREAD

**Issue by mezzovide** [FeroxRev/Pokemon-Go-Rocket-API#262]
Im sorry i cant help since i dont code in c#, but heres something that i hope someone would write it.

- after catch, checks if pokemon is 12 candies type
-  if yes, check amount of (candy available) for this pokemon type
-  if (candy available) < 600, transfer this pokemon
- else if (candy available) >= 600 && (this type pokemon amount in inventory < 50), stash this pokemon
-  else popup a lucky egg (required if the purpose is huge xp boost) and do evolve all this pokemon type at once

this way it will give huge xp boost by evolving cheap 50 12-candies pokemon type.

**Comment by mezzovide** [comment]
and we need to override transfer all duplicate pokemon (with a whitelist probably), in order to keep 12-candies type pokemon for the purpose

**Comment by kevvv** [comment]
Chiming in, with the rate that this evolves pokemon, it could do something like 150-200 evo's in that 30 min window, if not more.

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
