### ISSUE TITLE
different collor for messages

### ISSUE THREAD

**Issue by Fedorus** [FeroxRev/Pokemon-Go-Rocket-API#263]
The main interest is to see pokemon`s CP. So I could fast scroll the console and see what`s good and bad.

**Comment by D4nGuerrero** [comment]
This is in the code:

`public void Write(string message, LogLevel level = LogLevel.Info)
        {
            if (level > maxLogLevel)
                return;

            switch (level)
            {
                case LogLevel.Error:
                    System.Console.ForegroundColor = ConsoleColor.Red;
                    break;
                case LogLevel.Warning:
                    System.Console.ForegroundColor = ConsoleColor.Green;
                    break;
                case LogLevel.Info:
                    System.Console.ForegroundColor = ConsoleColor.White;
                    break;
                case LogLevel.Debug:
                    System.Console.ForegroundColor = ConsoleColor.Gray;
                    break;
                default:
                    System.Console.ForegroundColor = ConsoleColor.White;
                    break;
            }
            
            System.Console.WriteLine($"[{ DateTime.Now.ToString("HH:mm:ss")}] { message}");
        }`

You could edit, for example in Logic.cs, any line with Logger.Write and at the end it will have , LogLevel.Info. You can change Info to Error/Warning/Debug or add your own case.


But I would like to know if it's possible to display  2 colors in one line?

**Comment by Fedorus** [comment]
If you`ll use Console.Write() instead of WriteLine  you can

**Comment by Fedorus** [comment]
Done the trick to me. The CP of pokemon after catch marked RED

if (caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchSuccess)
                {
                    var prevColor = System.Console.ForegroundColor;
                    Console.Write($"[{ DateTime.Now.ToString("HH:mm:ss")}] We caught a { pokemon.PokemonId} with CP ");
                    System.Console.ForegroundColor = ConsoleColor.Red;
                    Console.Write($"{encounter?.WildPokemon?.PokemonData?.Cp}");
                    Console.ForegroundColor = prevColor;
                    Console.WriteLine($" and CaptureProbability: {encounter?.CaptureProbability.CaptureProbability_.First()} using a {pokeball} in {Math.Round(distance)}m distance", LogLevel.Error);
                }
                else
                {
                    var prevColor = System.Console.ForegroundColor;
                    Console.Write($"[{ DateTime.Now.ToString("HH:mm:ss")}] { pokemon.PokemonId}  with CP ");
                    System.Console.ForegroundColor = ConsoleColor.Red;
                    Console.Write($"{encounter?.WildPokemon?.PokemonData?.Cp}");
                    Console.ForegroundColor = prevColor;
                    Console.WriteLine($"CaptureProbability: { encounter?.CaptureProbability.CaptureProbability_.First()} in { Math.Round(distance)}m distance { caughtPokemonResponse.Status} while using a { pokeball}..", LogLevel.Info);
                }

**Comment by D4nGuerrero** [comment]
Used Console.Write to use more colors, example.


![2colors](https://cloud.githubusercontent.com/assets/20586092/17046324/a3bf7742-4f97-11e6-9596-c8ea38089445.png)

Now to tidy it up, lol.

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
