### ISSUE TITLE
Feature Request:  Interaction with gyms

### ISSUE THREAD

**Issue by cysteve** [FeroxRev/Pokemon-Go-Rocket-API#267]
Hi there.   I would like to see this feature !

- First just collect the gym reward if available
- Then later maybe interact with gyms too, and if there is a free slot put something there  (maybe later based on rules)
- And last,  fighting / training in gyms would be the cherry on the cake.  even just randomly picking fights and winning a few with blind button pushing would be better than just discarding those overstocked potions/elixirs. (later maybe include CP check? auto teams based on weaknesses? Battle Logic? and things i can't think of yet )

I do not know what would be even  possible...

**Comment by Meeplez** [comment]
It was said before, feature requests arenot looked through, your welcome to make a pull though.

**Comment by jshield** [comment]
I argue this should not be mainline as it would be highly unethical/immoral. Catching pokemon and spinning pokestops do not harm other players, participating in the Gyms however do.

**Comment by problemz** [comment]
Yeah - please don´t add it. Would be a step too far ... it´s ok to farm XP to get to the level cap asap and focus on the perfect IV/Movesets. But please don´t let code fight in gyms (of course with (nearly) perfect dodges)
