### ISSUE TITLE
mono on ubuntu

### ISSUE THREAD

**Issue by chun-hung** [FeroxRev/Pokemon-Go-Rocket-API#272]
Ask Google login only ,No Ptc login
Seems like can't load config file

**Comment by jshield** [comment]
Mono is not currently a supported target, if you want to fix it you can submit a PR request.

**Comment by zaitsevyan** [comment]
@chun-hung You need to add UserSettings.Desiner.cs to project and change default values there.

**Comment by gligi** [comment]
how did you get it work on mono? i get this:
 Unhandled exception: System.TypeInitializationException: The type initializer for 'PokemonGo.RocketAPI.Console.UserSettings' threw an exception. ---> System.InvalidProgramException: Invalid IL code in System.Configuration.Provider.ProviderBase:.ctor (): method body is empty.

**Comment by jshield** [comment]
Implement your own ISettings provider and remove all references to system.configuration as it is not completely implemented on mono.
