### ISSUE TITLE
Candy saving

### ISSUE THREAD

**Issue by Esummoner** [FeroxRev/Pokemon-Go-Rocket-API#274]
Please let us add a value of candy we want to save before auto evolve starts to work.

**Comment by Iterer** [comment]
In the `Logic.cs` if you don't wan't evolution of pokemons you can delete the `await EvolveAllPokemonWithEnoughCandy();`, line in the `public async Task PostLoginExecute()`. Moreover you should wait for the GUI, I'm sure these features would be added in it.

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
