### ISSUE TITLE
0 XP when pokestop is further away

### ISSUE THREAD

**Issue by TFMvdBroek** [FeroxRev/Pokemon-Go-Rocket-API#276]
Seems to be fixed when a delay is added before TP and before farming:

`var distance = Navigation.DistanceBetween2Coordinates(_client.CurrentLat, _client.CurrentLng, pokeStop.Latitude, pokeStop.Longitude);
if (distance > 300) await Task.Delay(10000);
var update = await _client.UpdatePlayerLocation(pokeStop.Latitude, pokeStop.Longitude, _clientSettings.DefaultAltitude);
if (distance > 300) await Task.Delay(10000);
var fortInfo = await _client.GetFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);`

**Comment by Iterer** [comment]
You wanna add a wait delay of 10 seconds for a soft ban duration of 10 seconds or less, the better way should be to check if the "fort" is not too far but it will slow down the bot. 
Anyway just wait for the human walking pull, it should solve the problem.

**Comment by TFMvdBroek** [comment]
This would ofc be a better solution. But until this is implemented, i dont see the problem in waiting a few sec.

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
