### ISSUE TITLE
Google change Account

### ISSUE THREAD

**Issue by dontCare123** [FeroxRev/Pokemon-Go-Rocket-API#277]
Im using the newest Version,
how can I change my account? 

Its always using the Account you logged in at the beginning, doesnt matter if restart it

**Comment by Iterer** [comment]
You just have to open the `PokemonGo.RocketAPI.Console.exe.config` file and change your information in it.

**Comment by dontCare123** [comment]
Where? There are 2 Configs, and I see nothing with my email used

**Comment by Iterer** [comment]
Id you use Visual Studio you can open `UserSettings.settings` in the project `PokemonGo.RocketAPI.Console`, it will help you to configure the `PokemonGo.RocketAPI.Console.exe.config` file.

**Comment by dontCare123** [comment]
Ok, i found it but there is nothing else than my coords
Google Refresh is empty

**Comment by Esummoner** [comment]
Got to appdata/local on your drive, you should see a PokeGO folder there, inside somewhere is a user settings file, remove it.

**Comment by dontCare123** [comment]
There is No Pokemon GO folder n Appdata, in both COnfigs there isnt something like my Email

Could u pls get clear  advice? I dont understand this

**Comment by dontCare123** [comment]
http://imgur.com/a/rQPb5 http://imgur.com/a/H2PaS

**Comment by Esummoner** [comment]
To make it easier for you , press windows key + r in the window that pops up type or copy paste : %localappdata%

**Comment by goldxero** [comment]
people like you should not be using a computer

**Comment by goldxero** [comment]
and the servers are down so do the math, nothing wrong with the bot

**Comment by dontCare123** [comment]
People like you shouldnt be allowed to help...
I went to  %appdata% before, saw no Pokemon GO, searched for Programs 86x also found nothing so I asked here

Its inpolite to insult me like this :-1:
