### ISSUE TITLE
Don't transfer perfect IV mon's but change their name to include 15IV

### ISSUE THREAD

**Issue by Trical** [FeroxRev/Pokemon-Go-Rocket-API#284]
Don't transfer perfect IV mon's but change their name to include "perfect" or "15iv" etc

**Comment by Esummoner** [comment]
Seriously dont rename pokemons.

**Comment by Trical** [comment]
Too obvious?

**Comment by dreadylein** [comment]
Not api related. Feel free to submit a PR for logic improvments
