### ISSUE TITLE
Pokemon evolve/transfer based on IV Calculation

### ISSUE THREAD

**Issue by vbeersma** [FeroxRev/Pokemon-Go-Rocket-API#287]
The real power of the pokemon is not based on CP but on IV index, which is calculated based on different values. This indicates a probability chance of the pokemon being worst possible (0.0%) till pokemon being perfect (100.0%).

See: [iv calc](https://pokeassistant.com/main/ivcalculator)

**Comment by FeroxRev** [comment]
Check latest commits
