### ISSUE TITLE
InvalidResponseException after constantly querying for about 30min

### ISSUE THREAD

**Issue by lx223** [FeroxRev/Pokemon-Go-Rocket-API#29]
Hi there,

After about 30m of calling various APIs, specially about getting inventory, it starts to throw the following exception. Do you happen to know anything about it? 

Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Work\PoGo\PoGoApiCSharp\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 20

**Comment by FeroxRev** [comment]
you will need to call login again, i will probably add automated re-authentication soon

**Comment by lx223** [comment]
Ah, makes sense. Thanks!

**Comment by lx223** [comment]
An alternative might be having the API raise the correct exception for such a case, e.g. AuthenticationExpiredException so that code using it can handle it correctly?
