### ISSUE TITLE
Limit the "We are within 40 meters of the target, attempting to interact." messages pls

### ISSUE THREAD

**Issue by VWPole** [FeroxRev/Pokemon-Go-Rocket-API#292]
its a bit annoying to watch when before sth happens this message gets spammed 20 times

**Comment by DaniilSokolyuk** [comment]
I think need change text color for walking messages

**Comment by RyuIV** [comment]
Yea, it's a bit to much of lime green for my eyes tbh

**Comment by FeroxRev** [comment]
Think this is fixed
