### ISSUE TITLE
Cant catch Pokemon and interact with pokestops

### ISSUE THREAD

**Issue by Th3C0D3R** [FeroxRev/Pokemon-Go-Rocket-API#297]
i get 0 xp if it interacts with the pokestop and every pokemon is CatchFlee.
but when i try it on Bluestack ingame everythings working

**Comment by shejk0** [comment]
Check if your inventory isn't full.

**Comment by Th3C0D3R** [comment]
nop its half full and every pkmn is running away

**Comment by shejk0** [comment]
Pokemon "bag" also isn't full? :P

**Comment by Ricktza** [comment]
Sounds like a softban, make sure you set Latitude and Longitude.

**Comment by Th3C0D3R** [comment]
its set to default or what i have to set it ^^ i think default should work fine

**Comment by Ricktza** [comment]
Default will get you banned if it's very far from another device or a past location.
the server will of seen you teleport across the world for example resulting in a softban.

**Comment by shejk0** [comment]
Default location is Amsterdam, if you have set in BlueStack another location you are soft banned. Which means you can't catch pokemons nor use poke stops or fight in gyms for some time.

**Comment by Th3C0D3R** [comment]
soooooo ok thanks ^^ now i understand ^^ then maybe i should change it
