### ISSUE TITLE
ExecuteFarmingPokestops Error (SkipLastField)

### ISSUE THREAD

**Issue by icetroll** [FeroxRev/Pokemon-Go-Rocket-API#31]
Hey man. Came across this error when i was letting the bot run.

From a quick look it looks like it start processing the packets before it gets all the packets. 

Tell me if you need any help, currently free.

Error:
`Additional information: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing`

**Comment by Maufeat** [comment]
That message should be not displayed if you have the most recent Version. But that problem is Server related, so nothing you / we can do there atm.

**Comment by FeroxRev** [comment]
Server related issues, handling will be fixed later
