### ISSUE TITLE
client.GetInventory(); returning id: 0 for pokemon

### ISSUE THREAD

**Issue by jakesteele** [FeroxRev/Pokemon-Go-Rocket-API#32]
client.GetInventory();

I recently added a release pokemon addition. After debugging to find out why the return message was Failed I realized the pokemon, id, property is 0 in all the pokemon returned. Is there a different api call I should be calling to get the correct information?

**Comment by ArcticXWolf** [comment]
I was doing the same xD
I already asked @FeroxRev in reddit, why this happened.

**Comment by martin-podlubny** [comment]
Explained the the problem and a fix on a different issue :) Hope it helps: https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/17#issuecomment-233811868

**Comment by ArcticXWolf** [comment]
Yeah, I created a pull request for a fix.

**Comment by FeroxRev** [comment]
PR merged
