### ISSUE TITLE
Where can I login with my google acc?

### ISSUE THREAD

**Issue by Betim123** [FeroxRev/Pokemon-Go-Rocket-API#34]
Im in Settings.cs:

        public const bool UsePTC = false;
        public const string PtcUsername = "User";
        public const string PtcPassword = "alligator2";
        public const string DeviceId = "cool-device-id";
        public const string Email = "fake@gmail.com";
        public const string ClientSig = "fake";
        public const string LongDurationToken = "fakeid";
        public const double DefaultLatitude = 10;
        public const double DefaultLongitude = 10;

I changed UsePTC to false...
what now?

**Comment by DaniilSokolyuk** [comment]
Read readme, use Charles

**Comment by ArcticXWolf** [comment]
Also, as I am not using github soo much, but aren't the issues a place to commit bugs and improvements?
I dont think this is a place for support questions, there is a reddit post for that.

But to not leave you with no answer:
install charles, intercept your login on the phone and update the fields (deviceId, email, clientsig) in setting.cs accordingly.

**Comment by FeroxRev** [comment]
@ArcticXWolf Correct, leave this to bugs please

**Comment by EnigmaIsWorking** [comment]
> But to not leave you with no answer:
install charles, intercept your login on the phone and update the fields (deviceId, email, clientsig) in setting.cs accordingly.

Thank you for this advice.
unfortunately on reddit are the hints not so usefull

> Download VS, edit config, run, taadaa

> Open Settings.cs in the PokemonGo.RocketAPI project and setup your account data (toggle UsePtc to true or false depending on your login method)
Click start -> wait for the console to go idle for about a minute or the program to crash -> repeat this step infinitely

Could you Merge an easier GoogleAccount log in like https://github.com/Mila432/Pokemon_Go_API here? ` public static string googleLogin(string user, string password)
        {
            Debug.WriteLine($"[!] Google login for: {user}");
            var first = "https://accounts.google.com/o/oauth2/auth?client_id=848232511240-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email";
            var second = "https://accounts.google.com/AccountLoginInfo";
            var third = "https://accounts.google.com/signin/challenge/sl/password";
            var last = "https://accounts.google.com/o/oauth2/token";
            using (var clientHandler = new HttpClientHandler())` ...

**Comment by FeroxRev** [comment]
Google login is being reworked atm, please hold :)

**Comment by EnigmaIsWorking** [comment]
You are doing a great favour to all dads outside, who cannot play with their children because they are bound to their chair at work.

 

Von: Ferox [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. Juli 2016 12:49
An: FeroxRev/Pokemon-Go-Rocket-API <Pokemon-Go-Rocket-API@noreply.github.com>
Cc: EnigmaIsWorking <martin@koltonowski.de>; Comment <comment@noreply.github.com>
Betreff: Re: [FeroxRev/Pokemon-Go-Rocket-API] Where can I login with my google acc? (#34)

 

Google login is being reworked atm, please hold :)
