### ISSUE TITLE
StartGymBattle doesn't return a correct response

### ISSUE THREAD

**Issue by unnown** [FeroxRev/Pokemon-Go-Rocket-API#36]
the following returns basicly an empty response.

```
            var mypokemon = inventory.InventoryDelta.InventoryItems.Select(i => i.InventoryItemData?.PokemonData)
                    .Where(p => p != null && p.PokemonId > 0).OrderByDescending(CalculatePokemonPerfection).Take(6).
                    Select(pok => pok.Id);

var startBattle = await client.Fort.StartGymBattle(gym.Id, gymState.Memberships.First().PokemonData.Id, mypokemon);

```

**Comment by Alexander3500** [comment]
Hey how do i enter commands? Where do I enter my command?? Please and thank you! Im new to this I have no idea how to enter commands I want to see how many items i have and I want to recycle some things :\ Thank you!

**Comment by unnown** [comment]
this is an api, if you want botting i suggest you google pokemon go rocket bot or pokemon go rocket gui

**Comment by unnown** [comment]
Nvm seems to be a problem with protos. closed
