### ISSUE TITLE
Is Egg Distance implemented?

### ISSUE THREAD

**Issue by mpah** [FeroxRev/Pokemon-Go-Rocket-API#38]
EggKmWalkedStart & EggKmWalkedTarget just return 0 and max egg distance.

**Comment by FeroxRev** [comment]
It does return values here, are you sure you're looking at an egg?

**Comment by Xeeynamo** [comment]
I confirm that EggKmWalkedStart is equal to 0 on incubated eggs, but EggKmWalkedTarget contains the correct value.
