### ISSUE TITLE
HELP CATCH

### ISSUE THREAD

**Issue by golditaradipa** [FeroxRev/Pokemon-Go-Rocket-API#39]
how to catch pokemon with great ball instead of normal, because when i try to catch greatball , its always fail, thankyou

**Comment by HelloKitty** [comment]
You changed Pokeball = (int) MiscEnums.Item.ITEM_POKE_BALL and it didn't work?

**Comment by golditaradipa** [comment]
yes pretty sure, bot doesn't work when i'm out of pokeball,

**Comment by FeroxRev** [comment]
so you're out of pokeballs, that's nog a bug!

**Comment by golditaradipa** [comment]
out of pokeball, but i have great ball, so greatball doesn't work

**Comment by FeroxRev** [comment]
you can now supply PokeBallType to CatchPokemon, so you can add logic for using great ball   #49  :)

**Comment by golditaradipa** [comment]
got changed to this Pokeball = (int)MiscEnums.Item.ITEM_GREAT_BALL,
