### ISSUE TITLE
On google login, what is LongDurationToken and DeviceID?

### ISSUE THREAD

**Issue by ardaozkal** [FeroxRev/Pokemon-Go-Rocket-API#4]
![thing](https://0ws.pw/b50i.png)

This is what charles shows, is the "LongDurationToken" "Token" and "DeviceID" "androidID"?

If so, I can't log in, and it is probably a bug.

**Comment by FeroxRev** [comment]
It's the token that starts with oath..6blabla

**Comment by ardaozkal** [comment]
ok, token is correct (oauth2rtsomething for me). Is device id "35edsomething" or "848something"?

**Comment by FeroxRev** [comment]
correct

**Comment by ardaozkal** [comment]
Ok, I uncommented some lines I commented before and it somehow works now, thanks.

Also deviceid seems like it is the numeric (latter) one
