### ISSUE TITLE
Suggestion- maybe we should make a context class?

### ISSUE THREAD

**Issue by OranShuster** [FeroxRev/Pokemon-Go-Rocket-API#40]
right now the current player information is kinda scatterd between the classes while each of them uses the Client class to get information. maybe we should move to a public context class to have all the current player location and information with methods to update location and so on

**Comment by ArcticXWolf** [comment]
Yeah, I think so too. Maybe we should also create some extra classes to simplify working with Items, Pokemons in Inventory, etc.

**Comment by OranShuster** [comment]
much work is needed on the actual algorithem. right now we choose a random pokestop/pokemon instead of choosing closer ones

**Comment by ArcticXWolf** [comment]
But now that I think about it, this is meant to be just the C# api and the console project is just an example of how to use it, isn't it? So maybe we should focus to improve the API and split a bot into a subproject/repo.

**Comment by jshield** [comment]
I was just going to recommend that @ArcticXWolf

**Comment by OranShuster** [comment]
yeah... right now the client is in the API when it really shouldn't be

**Comment by pkiers** [comment]
Maybe instead of a console we could create a simple MVC web application. Show a google map with al items found. So you can also just click on the map and move there.

Also list of all inventory so you can just remove items from there.

**Comment by ArcticXWolf** [comment]
I would just leave it how it is, because the console application is just a demonstration. no need to get a full fledged client in here.

Everyone wanting to build such an application can just compile this project into an api and use it in a new project. That's how apis work..
But maybe @FeroxRev should let us know, how he sees it.

**Comment by Maufeat** [comment]
Yeah, you missed that point on all of that. It actually should be just a library to develop with and the console is project is just the "test" class. If you want to create applications with it, do that as an seperated project and use the Rocket API Library for the functions.

**Comment by FeroxRev** [comment]
Yes, i'm going to refactor the code today after merging the pull requests in that belong to the library

**Comment by FeroxRev** [comment]
@pkiers 

I would prefer a WPF application over a MVC web app. Unless you can convince me for the latter ;)

**Comment by pkiers** [comment]
@FeroxRev WPF just as fine,, but as @ArcticXWolf mentions would be good to split the API part from it fully. I always love a clean API :)

**Comment by FeroxRev** [comment]
Bot logic and API will be separated today. Closing issue for now
