### ISSUE TITLE
Pokemon CP

### ISSUE THREAD

**Issue by blackms** [FeroxRev/Pokemon-Go-Rocket-API#41]
Hello I'm trying to get the Pokemon CP During the encounter:

`foreach (var pokemon in pokemons)
            {
                var update = await client.UpdatePlayerLocation(pokemon.Latitude, pokemon.Longitude);
                var encounterPokemonRespone = await client.EncounterPokemon(pokemon.EncounterId, pokemon.SpawnpointId);`

But inside the pokemon object I can't see the CP vaule, where is it?

**Comment by ArcticXWolf** [comment]
The EncounterResponse does not seem to be correct.

Compare ours:

    message EncounterResponse {
        int32 unknown1 = 1;
        int64 unknown2 = 2;
        string api_url = 3;
        Unknown6 unknown6 = 6;
        Unknown7 unknown7 = 7;
        repeated Payload payload = 100;
        string errorMessage = 101; //Should be moved to an error-proto file if error is always 101 field
        
        message Unknown6 {
            int32 unknown1 = 1;
            Unknown2 unknown2 = 2;
            message Unknown2 {
                bytes unknown1 = 1;
            }
        }
        message Unknown7 {
            bytes unknown71 = 1;
            int64 unknown72 = 2;
            bytes unknown73 = 3;
        }
        message Payload {  
	    int32 Pokemon = 1;
	    int32 Background = 2;
	    int32 Status = 3;
	    int32 CaptureProbability = 4;
        } 
    }

To this one (https://github.com/tejado/pgoapi/blob/master/pgoapi/protos/RpcSub.proto):

    message EncounterResponse {
        optional WildPokemon wild_pokemon = 1;
        optional Background background = 2;
        optional Status status = 3;
        optional CaptureProbability capture_probability = 4;
        
        enum Background {
            PARK = 0;
            DESERT = 1;
        }
        
        enum Status {
            ENCOUNTER_ERROR = 0;
            ENCOUNTER_SUCCESS = 1;
            ENCOUNTER_NOT_FOUND = 2;
            ENCOUNTER_CLOSED = 3;
            ENCOUNTER_POKEMON_FLED = 4;
            ENCOUNTER_NOT_IN_RANGE = 5;
            ENCOUNTER_ALREADY_HAPPENED = 6;
            POKEMON_INVENTORY_FULL = 7;
        }
    }
    
    message WildPokemon {
        optional fixed64 encounter_id = 1;
        optional int64 last_modified_timestamp_ms = 2;
        optional double latitude = 3;
        optional double longitude = 4;
        optional string spawnpoint_id = 5;
        optional PokemonData pokemon_data = 7;
        optional int32 time_till_hidden_ms = 11;
    }

Maybe @FeroxRev we should generally update our protos like these from tejado, because they seem to be 1. more recent and 2. better structured ( for example no 2 seperate PokemonType for MapResponse and InventoryResponse).

**Comment by FeroxRev** [comment]
Needed to look at how to handle proto's anyway. I'll prio this, thanks

**Comment by blackms** [comment]
I already saw the other issue opened from you. Took the correct code thanks.
