### ISSUE TITLE
Supply PokeBallType as parameter for catching a Pokemon

### ISSUE THREAD

**Issue by Newkz** [FeroxRev/Pokemon-Go-Rocket-API#43]
Using better pokeballs on higher CP pokemons would be nice.

Also, If you run out of normal pokeball's you will get the "got away" msg all the time, even though you have better pokeballs available. Usually happens if your inventory is full.

**Comment by Maufeat** [comment]
There is currently no "logic" behind that. You can switch Pokeballs when changing it on the "client.CatchPokemon" method, there is "ITEM_POKE_BALL" defined, just change that to "ITEM_ULTRA_BALL" or "ITEM_GREAT_BALL"

**Comment by ArcticXWolf** [comment]
My PR is ofcourse not the filnal solution, but at least you can now temporarly switch it now.

**Comment by thetemplar** [comment]
Where can I find how many Balls I have?

**Comment by ArcticXWolf** [comment]
You must look into your inventory, items with itemId 1 are for example Pokeballs. Look in the MiscEnums.Item Enum to map itemIds to names.

**Comment by tw88** [comment]
superballs have the ID: 2 -> you could check this and use it to alter the switch
