### ISSUE TITLE
Randomhelper

### ISSUE THREAD

**Issue by nfettinger** [FeroxRev/Pokemon-Go-Rocket-API#45]
I get the following error when using RandomHelper in other projects.
Code I added in PoGo.NecroBot.Logic
`_rand = new RandomHelper();
_rand.GetLongRandom(long, long);`
Error I get
`error CS0176: Member 'RandomHelper.GetLongRandom(long, long)' cannot be accessed with an instance reference; qualify it with a type name instead`

From what I can tell, removing the static quantifier from `GetLongRandom` fixes the issue. Not sure if this the correct approach or not.

**Comment by unnown** [comment]
this has nothing to do with this api?
but if removing the static fixes your issue, than it seems like the correct sollution

**Comment by nfettinger** [comment]
I'm just assuming this is a bug with the api, and I am the first one to hit it. I am not positive though which is why I am asking.

**Comment by bmallin** [comment]
This is _not_ a bug with the api. It is a problem with how you are calling the method. Since `GetLongRandom` is a static method, it cannot be accessed via an instance. `RandomHelper.GetLongRandom(long, long)` is how you want to call it.
