### ISSUE TITLE
Use Lucky Egg Request

### ISSUE THREAD

**Issue by Corlobin** [FeroxRev/Pokemon-Go-Rocket-API#5]
Hello, first, I wanna congratulations you guys, nice work.

I am trying to understand your code and contribute on it. 

I would like to know how I use items. I looked at UseCaptureItems but I dont think what I am doing is right.

Is it right?

```
public async Task UseLuckyEgg(ulong encounterId, string spawnPointId)
        {
            var inventoryItems = await _inventory.GetItems();
            var eggs = inventoryItems.Where(p => (ItemId)p.Item_ == ItemId.ItemLuckyEgg);
            var egg = eggs.FirstOrDefault();

            if (egg == null)
                return;

            var useLuckyEgg = await _client.UseCaptureItem(encounterId, AllEnum.ItemId.ItemRazzBerry, spawnPointId);
            Logger.Write($"Use LuckyEgg. Remaining: {egg.Count}", LogLevel.Info);
            await Task.Delay(3000);
        }
```

Is there any Response for Use items like Incubators or anything?

**Comment by mad-it** [comment]
These are probably completely different requests since "UseCaptureItems" are related to capturing a pokemon(berry, pokeballs).

**Comment by FeroxRev** [comment]
Lucky eggs are implemented
