### ISSUE TITLE
License change to MIT

### ISSUE THREAD

**Issue by itsff** [FeroxRev/Pokemon-Go-Rocket-API#53]
Would you consider a dual license of just re-licensing under the MIT/BSD style license?

**Comment by FeroxRev** [comment]
nope

**Comment by itsff** [comment]
Why not? 

More freedom = more contributors

**Comment by FeroxRev** [comment]
Open source for the win

**Comment by itsff** [comment]
Nah, I myself prefer

![image](https://cloud.githubusercontent.com/assets/918299/17235655/770df19e-5508-11e6-9c01-01ebbd862ac0.png)

But at least the question is answered, in case anyone else wants to know about the license choice in the future.
