### ISSUE TITLE
Can't login with google

### ISSUE THREAD

**Issue by TheUltyLegend** [FeroxRev/Pokemon-Go-Rocket-API#56]
![afcdasdd](https://cloud.githubusercontent.com/assets/20707695/17220984/0cac0478-54f2-11e6-9f59-e3781f022610.png)

When I open necrobot happen this, please help.

**Comment by centupede** [comment]
same. though thank you for the guy who took the trouble to fix the problem. even when I fill out the ggl name and pass, the program crushes after launching it. btw, could someone teach me how to not auto update? coz it was ok for some ppl who already had auth.

**Comment by TheUltyLegend** [comment]
@centupede But it's working for you?

**Comment by FeroxRev** [comment]
This isn't Necrobot

**Comment by adskimomo** [comment]
if you use 2fa try https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/57 and create an app password
