### ISSUE TITLE
No way to log in with 2-step authentication for organization gmails

### ISSUE THREAD

**Issue by Nick-McKay** [FeroxRev/Pokemon-Go-Rocket-API#57]
Most all Gmail accounts that require 2-step authentication do not allow for application-specific passwords. Is there any way around this, or could the web-login be implemented?

**Comment by TehPirat3** [comment]
You can login with 2-step auth accounts using https://security.google.com/settings/security/apppasswords iirc

**Comment by Nick-McKay** [comment]
That only works if the organization or domain hosting your email allows you security permissions. For example school, company, organization, or public email domains typically disallow users access to these permissions and thus they cannot establish application-specific passwords.

**Comment by Sterling674** [comment]
From what i have heard right now two step authentication is not supported.

**Comment by daf82hvfe2sfd** [comment]
I'm not sure if I follow. I am able to create app specific passwords with no problems and I'm using a regular gmail account I created at home. I have 2 step enabled and by using the app password instead of my regular password I am able to log in.

**Comment by FeroxRev** [comment]
I can log in with 2fa creating an app password as well, so closing

**Comment by reid-vollett** [comment]
For organization gmail accounts (ie, school gmail accounts), 2FA App Passwords are disabled and one cannot be set. After logging into the gmail account, it requires an extra login page through the organization. It was previously working around the 26th.
