### ISSUE TITLE
Move Settings out of the API project

### ISSUE THREAD

**Issue by jshield** [FeroxRev/Pokemon-Go-Rocket-API#57]
as per #47

Thinking about it more, I am not sure if App.config is the best place for it, perhaps either replace the Settings class with an ISettings interface and implement providers that can source the values from different locations.

My argument for this is that this library would benefit from being ported to Xamarin (iOS/Android) or .NET core as a PCL in the future, App.config does not exist on those platforms.

**Comment by FeroxRev** [comment]
I'm up for both really

**Comment by davidmann4** [comment]
I guess we already have it by now? I never coded it btw

**Comment by jshield** [comment]
Yeah we have it now. Seems to be working ok.
