### ISSUE TITLE
Significance of $ before string and occasional ? in front of variable?

### ISSUE THREAD

**Issue by kp0296** [FeroxRev/Pokemon-Go-Rocket-API#58]
Why does almost all of the strings in the SC contain a $ infront of it? For example:

System.Console.WriteLine(caughtPokemonResponse.Payload[0].Status == 1 ? $"[{DateTime.Now.ToString("HH:mm:ss")}] We caught a {GetFriendlyPokemonName(pokemon.PokedexTypeId)}" : $"[{DateTime.Now.ToString("HH:mm:ss")}] {GetFriendlyPokemonName(pokemon.PokedexTypeId)} got away..");

Also occasional ? included in variable names such as:

return name?.Substring(name.IndexOf("Pokemon") + 7);

These are coming up as syntax errors in my IDE so why are they there? Am I missing some extension or something?

**Comment by FeroxRev** [comment]
Update to latest VS

**Comment by jshield** [comment]
$ is string interpolation a new C# 6 feature.
