### ISSUE TITLE
Client methods for dropping items (think shitty Poke Balls)

### ISSUE THREAD

**Issue by martinp-rg** [FeroxRev/Pokemon-Go-Rocket-API#59]
Farming many pokestops? Why not drop shitty items like the plain old Poke Ball to have more room for them Great and Ultra balls?

(feature-request)

**Comment by xEnt22** [comment]
agreed, though i find potions/super potions/raspberries to be more annoying!

**Comment by thetemplar** [comment]
DropItem would be nice indeed.

**Comment by FeroxRev** [comment]
Closing and updating in wiki
