### ISSUE TITLE
Player.GetOwnProfile() not found?

### ISSUE THREAD

**Issue by TehPirat3** [FeroxRev/Pokemon-Go-Rocket-API#59]
Using latest master, GetOwnProfile not found nor do I see it on here in Player

**Comment by unnown** [comment]
var test = client.Player.GetPlayer();
i assume you mean something else, but this gets your player profile

**Comment by TehPirat3** [comment]
Thanks, no that is what I wanted. I figured it out eventually but was confused due to the usage example in the ReadMe
