### ISSUE TITLE
Getting a timeout on updating player location

### ISSUE THREAD

**Issue by Martiveen** [FeroxRev/Pokemon-Go-Rocket-API#6]
This happens on the first few times.

At line in Program.cs:
var update = await client.UpdatePlayerLocation(pokeStop.Latitude, pokeStop.Longitude);

Exception details:
System.Threading.Tasks.TaskCanceledException was unhandled by user code
  HResult=-2146233029
  Message=Een taak is geannuleerd.
  Source=mscorlib
  StackTrace:
       bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bij System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       bij PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__0`2.MoveNext() in C:\Users\*\Source\Repos\Pokemon-Go-Rocket-API\PokemonGo\RocketAPI\Extensions\HttpClientExtensions.cs:regel 19
    --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
       bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bij System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       bij PokemonGo.RocketAPI.Client.<GetMapObjects>d__15.MoveNext() in C:\Users\*\Source\Repos\Pokemon-Go-Rocket-API\PokemonGo\RocketAPI\Client.cs:regel 233
    --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
       bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bij System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       bij PokemonGo.RocketAPI.Console.Program.<ExecuteFarmingPokestopsAndPokemons>d__2.MoveNext() in C:\Users\*\Source\Repos\Pokemon-Go-Rocket-API\PokemonGo\RocketAPI\Console\Program.cs:regel 52
    --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
       bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bij System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       bij PokemonGo.RocketAPI.Console.Program.<Execute>d__1.MoveNext() in C:\Users\*\Source\Repos\Pokemon-Go-Rocket-API\PokemonGo\RocketAPI\Console\Program.cs:regel 39
  InnerException:

**Comment by FeroxRev** [comment]
The TaskCancelled timeout i presume? Servers are kinda meh atm and I need to implement some things for bad servers =/

**Comment by Martiveen** [comment]
Ah, ill try tomorow again then.
