### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by AndyAndreich** [FeroxRev/Pokemon-Go-Rocket-API#60]
Can't login with last updates. Login and password is correct.
https://gyazo.com/1e59df8e35ddb25fd31b2a8ad9150161

**Comment by FeroxRev** [comment]
Check the inner exception and actual value of the error..

**Comment by unnown** [comment]
i logged in a lot, besides some lag it all works

**Comment by adskimomo** [comment]
if you use 2fa try https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/57 and create an app password
