### ISSUE TITLE
Client methods for using items (think lucky eggs)

### ISSUE THREAD

**Issue by martinp-rg** [FeroxRev/Pokemon-Go-Rocket-API#60]
Wouldn't all this farming be better if we automatically popped a Lucky Egg before doing 300+ evolutions programatically?

(feature-request)

**Comment by xEnt22** [comment]
eh surely you can log in and manually use a lucky egg before letting the bot do a mass evolution?

**Comment by FeroxRev** [comment]
Closing and updating wiki
