### ISSUE TITLE
Poke ball count can be determined to switch which poke ball

### ISSUE THREAD

**Issue by MonsterMMORPG** [FeroxRev/Pokemon-Go-Rocket-API#64]
```
               {  
                  "item":{  
                     "item":{  
                        "item":1,
                        "count":8
                     }
                  }
               }
```

item 1 : poke ball
item 2 : great ball
item 3 : ultra ball

**Comment by N3messys** [comment]
`        private static async Task<MiscEnums.Item> getBestBall(Client client, MapObjectsResponse.Types.Payload.Types.PokemonIds pokemonId)
        {
            var inventory = await client.GetInventory();

            var ballCollection = inventory.Payload[0].Bag.Items.Select(i => i.Item.Item).Where(p => p != null)
               .GroupBy(i => (MiscEnums.Item)i.Item)
               .Select(kvp => new { ItemId = kvp.Key, Amount = kvp.Sum(x => x.Count) })
               .Where(y => y.ItemId == MiscEnums.Item.ITEM_POKE_BALL
               || y.ItemId == MiscEnums.Item.ITEM_GREAT_BALL
               || y.ItemId == MiscEnums.Item.ITEM_ULTRA_BALL
               || y.ItemId == MiscEnums.Item.ITEM_MASTER_BALL);

            var pokeBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_POKE_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_POKE_BALL, Amount = 0 }).FirstOrDefault().Amount;
            var greatBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_GREAT_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_GREAT_BALL, Amount = 0 }).FirstOrDefault().Amount;
            var ultraBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_ULTRA_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_ULTRA_BALL, Amount = 0 }).FirstOrDefault().Amount;
            var masterBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_MASTER_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_MASTER_BALL, Amount = 0 }).FirstOrDefault().Amount;

            if (masterBallsCount > 0)
                return MiscEnums.Item.ITEM_MASTER_BALL;

            if (ultraBallsCount > 0)
                return MiscEnums.Item.ITEM_ULTRA_BALL;

            if (greatBallsCount > 0)
                return MiscEnums.Item.ITEM_GREAT_BALL;

            return MiscEnums.Item.ITEM_POKE_BALL;
        }`

This is a greedy way of choosing the ball. The LINQ code should be re-written tho.

**Comment by xolived** [comment]
private static async Task<MiscEnums.Item> getBestBall(Client client, MapObjectsResponse.Types.Payload.Types.PokemonIds pokemonId)
        {
            var inventory = await client.GetInventory();

            var ballCollection = inventory.Payload[0].Bag.Items.Select(i => i.Item.Item).Where(p => p != null)
               .GroupBy(i => (MiscEnums.Item)i.Item)
               .Select(kvp => new { ItemId = kvp.Key, Amount = kvp.Sum(x => x.Count) })
               .Where(y => y.ItemId == MiscEnums.Item.ITEM_POKE_BALL
               || y.ItemId == MiscEnums.Item.ITEM_GREAT_BALL
               || y.ItemId == MiscEnums.Item.ITEM_ULTRA_BALL
               || y.ItemId == MiscEnums.Item.ITEM_MASTER_BALL);

            var pokeBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_POKE_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_POKE_BALL, Amount = 0 }).FirstOrDefault().Amount;
            var greatBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_GREAT_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_GREAT_BALL, Amount = 0 }).FirstOrDefault().Amount;
            var ultraBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_ULTRA_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_ULTRA_BALL, Amount = 0 }).FirstOrDefault().Amount;
            var masterBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_MASTER_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_MASTER_BALL, Amount = 0 }).FirstOrDefault().Amount;

            if (masterBallsCount > 0)
                return MiscEnums.Item.ITEM_MASTER_BALL;

            if (ultraBallsCount > 0)
                return MiscEnums.Item.ITEM_ULTRA_BALL;

            if (greatBallsCount > 0)
                return MiscEnums.Item.ITEM_GREAT_BALL;

            return MiscEnums.Item.ITEM_POKE_BALL;
        }

This is a greedy way of choosing the 'best' ball for an encounter. The LINQ code however is convoluted. Should be easy to extend based on pokemon preferences.

**Comment by MonsterMMORPG** [comment]
@xolived  i am trying to make it work but not working since you use await task

`  private static async Task<int> getBestBall(Client client)
        {
            var inventory = await client.GetInventory();

            var ballCollection = inventory.Payload[0].Bag.Items.Select(i => i.Item.Item).Where(p => p != null)
               .GroupBy(i => (MiscEnums.Item)i.Item)
               .Select(kvp => new { ItemId = kvp.Key, Amount = kvp.Sum(x => x.Count) })
               .Where(y => y.ItemId == MiscEnums.Item.ITEM_POKE_BALL
               || y.ItemId == MiscEnums.Item.ITEM_GREAT_BALL
               || y.ItemId == MiscEnums.Item.ITEM_ULTRA_BALL
               || y.ItemId == MiscEnums.Item.ITEM_MASTER_BALL);

            var pokeBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_POKE_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_POKE_BALL, Amount = 0 }).FirstOrDefault().Amount;
            var greatBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_GREAT_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_GREAT_BALL, Amount = 0 }).FirstOrDefault().Amount;
            var ultraBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_ULTRA_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_ULTRA_BALL, Amount = 0 }).FirstOrDefault().Amount;
            var masterBallsCount = ballCollection.Where(p => p.ItemId == MiscEnums.Item.ITEM_MASTER_BALL).
                DefaultIfEmpty(new { ItemId = MiscEnums.Item.ITEM_MASTER_BALL, Amount = 0 }).FirstOrDefault().Amount;

            if (masterBallsCount > 0)
                return  await Task.FromResult((int)MiscEnums.Item.ITEM_MASTER_BALL);

            if (ultraBallsCount > 0)
                return await Task.FromResult((int)MiscEnums.Item.ITEM_ULTRA_BALL);

            if (greatBallsCount > 0)
                return await Task.FromResult((int)MiscEnums.Item.ITEM_GREAT_BALL);

                   return await Task.FromResult((int)MiscEnums.Item.ITEM_POKE_BALL);
        }

        public async Task<CatchPokemonResponse> CatchPokemon(ulong encounterId, string spawnPointGuid, double pokemonLat,
            double pokemonLng, Client client)
        {
            var customRequest = new Request.Types.CatchPokemonRequest()
            {
                EncounterId = encounterId,
                Pokeball = getBestBall(client),
                SpawnPointGuid = spawnPointGuid,
                HitPokemon = 1,
                NormalizedReticleSize = Utils.FloatAsUlong(1.950),
                SpinModifier = Utils.FloatAsUlong(1),
                NormalizedHitPosition = Utils.FloatAsUlong(1)
            };

            var catchPokemonRequest = RequestBuilder.GetRequest(_unknownAuth, _currentLat, _currentLng, 30,
                new Request.Types.Requests()
                {
                    Type = (int)RequestType.CATCH_POKEMON,
                    Message = customRequest.ToByteString()
                });
            return
                await
                    _httpClient.PostProto<Request, CatchPokemonResponse>($"https://{_apiUrl}/rpc", catchPokemonRequest);
        }`


**Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'System.Threading.Tasks.Task<int>' to 'int'	PokemonGo.RocketAPI	D:\74 pokemon go\CatcherStopperTransfer\PokemonGo\RocketAPI\Client.cs	519	Active**

**Comment by 0dinson** [comment]
I would love this feature to work, only using "worst" pokeball and stop working in case they run out is a really dumb reason for the bot not to work. 

Also, just using specific balls for some pokemon like all 3rd evolutions is great. Any way to change that to CP? Like use great ball 300+ and ultra ball 500+ 

Im not that into coding btw.. still downloading Visual Studio

**Comment by FeroxRev** [comment]
Closing and updating wiki
