### ISSUE TITLE
Catching Pokemon using specific Pokeball

### ISSUE THREAD

**Issue by martin-podlubny** [FeroxRev/Pokemon-Go-Rocket-API#65]
What if you encounter that MewTwo and your bot throws a shitty Pokeball at it? Should have mechanism for throwing a better ball if some logic determines to do so..

For logic, maybe have a list of pokemons to always use Ultraball on, maybe that Alakazam or something that you're missing in the Pokedex and really don't want to miss it :)

(feature-request)

**Comment by Maufeat** [comment]
I would let that logic decide on the CP level, I think the higher the CP the harder it gets to catch, rarity doesn't mean harder to catch in my experience at least.

**Comment by thetemplar** [comment]
How to determin the CP during combat? EncounterResponse and MapPokemon dont have the attributs.

**Comment by martin-podlubny** [comment]
@thetemplar EncounterOutProto has WildPokemonProto has PokemonProto has Cp :)

**Comment by MonsterMMORPG** [comment]
as a start we can start poke switch based on counts in bag

**Comment by thetemplar** [comment]
@martin-podlubny What am I missing here? I have the newest revision, but neither of those classes. I STRG-F the whole solution

**Comment by FeroxRev** [comment]
Closing and updating wiki
