### ISSUE TITLE
Niantic / Google API change for Pokemon GO? may need update all bots broken

### ISSUE THREAD

**Issue by Navyguy330** [FeroxRev/Pokemon-Go-Rocket-API#65]
Just an FYI

**Comment by CarlSchou** [comment]
Mine's working fine

**Comment by ifbatmanwasreal** [comment]
I've tried 4 different bots after Necro went down. To me that was the first cause that's what I used. But none are working now. So it seems like you're right.

CarlSchou, were you running for a while? Or did you just start the bot recently?

**Comment by Deske043** [comment]
All of mine arent working either..

**Comment by darkseid4nk** [comment]
would be nice if people shared what bots are currently working.

**Comment by GamespikeYT** [comment]
necro release 0.1.6 works for me

**Comment by Navyguy330** [comment]
Relog the bot close it and re open it

**Comment by ifbatmanwasreal** [comment]
Dude they did something with the API... All bots are down. API is how they connect

**Comment by Navyguy330** [comment]
Correct it was just changed, updated or what ever, why idk, MAYBE anti something, maybe just normal update. maybe to fix three step bug idk if not though not sure why else.  also you can login fine on your phone or even any apk like bluestacks or nox.

**Comment by GamespikeYT** [comment]
I started the release just now and that ine still works for some reason

**Comment by FeroxRev** [comment]
API is running fine here, it's logic related
