### ISSUE TITLE
Support level-up rewards

### ISSUE THREAD

**Issue by Misiu** [FeroxRev/Pokemon-Go-Rocket-API#66]
Hi there, first of all awesome API!
When we level-up in real game (on device) we get rewards,
Is this also supported by Your API?
How can we get those rewards?

**Comment by vmcall** [comment]
Player.GetLevelUpRewards(int level)

**Comment by ghost** [comment]
var Rewards = await _client.Player.GetLevelUpRewards(LevelHere)
use this code i call it just after the player has levelled up

**Comment by FeroxRev** [comment]
Done!
