### ISSUE TITLE
Bot tries to throw pokeballs even though it ran out (bug)

### ISSUE THREAD

**Issue by martin-podlubny** [FeroxRev/Pokemon-Go-Rocket-API#66]
This happened to me when my bag was too full, so I couldn't pickup more default pokeballs. I ran out, and simply had 0 pokeballs in my account (though I had 300 Great Balls). Client still keeps trying the throw `ITEM_POKE_BALL` and understandably every catch started failing.

Relevant issues (feature-requests):
- [Catching Pokemon using specific Pokeball #65](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/65)
- [Poke ball count can be determined to switch which poke ball #64](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/64)
- [Client methods for dropping items (think shitty Poke Balls) #59](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/59)

There's no right solution to this problem, but dropping shitty items so that we postpone running out of pokeballs, or could fallback on better balls.

**Comment by MonsterMMORPG** [comment]
have you figured out a solution

**Comment by martin-podlubny** [comment]
Haven't had time to work on POGO, busy with my dayjob :D I'll be looking into these things at around 23:00 UTC today.

**Comment by FeroxRev** [comment]
Closing and updating wiki

**Comment by michaelowens** [comment]
Perhaps a limit per item type, so you can configure what items you might want to farm.
