### ISSUE TITLE
Automatic Reconnect

### ISSUE THREAD

**Issue by Newkz** [FeroxRev/Pokemon-Go-Rocket-API#67]
After 10-15 minutes it stops gathering anything, presumable because it lost connection to the server. At which point you need to restart it. An automatic reconnect feature would be nice :)

**Comment by xolived** [comment]
It's not the connection. The bot gets the map data at start then goes through every pokeStop received initially. After that, it just runs out of work and stops. You can wrap the search function in an loop ( think of while(true) ) and it will run contiguously.
