### ISSUE TITLE
Add Delay to prevent empty result

### ISSUE THREAD

**Issue by Vega2015** [FeroxRev/Pokemon-Go-Rocket-API#68]
The api will return empty values if you hammer on it with request i added a delay in HTTPClientExtension

 {
            Debug.WriteLine($"Requesting {typeof(TResponsePayload).Name}");

```
        System.Threading.Thread.Sleep(200);
        var response = await PostProto<TRequest>(client, url, requestEnvelope);

        if (response.Returns.Count == 0)
            throw new InvalidResponseException();
```

**Comment by FeroxRev** [comment]
Exactly :)

**Comment by FeroxRev** [comment]
but not going to add this to api, bot logic it is!

**Comment by royaal89** [comment]
where can i edit this? im not that good at things like this, sorry if this question is completly stupid
