### ISSUE TITLE
bot just run fine and it bugged and now it dont work at all after getting new update

### ISSUE THREAD

**Issue by royaal89** [FeroxRev/Pokemon-Go-Rocket-API#69]
[00.28.32](ERROR) System.IO.FileNotFoundException: Finner ikke filen C:\Users\Roy \Desktop\NecroBot-master\New Track.GPX.
Filnavn: C:\Users\Roy \Desktop\NecroBot-master\New Track.GPX
   ved System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   ved System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   ved System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   ved System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   ved System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   ved System.IO.File.ReadAllText(String path)
   ved PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.GetGpxTracks(ISession session) i C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:linje 144
   ved PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__0.MoveNext() i C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:linje 23
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   ved PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() i C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:linje 38
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   ved PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() i C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:linje 34

know whats wrong?

**Comment by FeroxRev** [comment]
This is not api

**Comment by ghost** [comment]
The error seems to be with the amount of requests its making to the server make the delay in necro to about 5 seconds this is a temporary fix ive got working at the moment

**Comment by royaal89** [comment]
where can i change delay?

and thank you so much for answering me!!:)

**Comment by Navyguy330** [comment]
all of a sudden it breaks? something changed lol

**Comment by royaal89** [comment]
i have no idea what happend, it was running fine and then error came, after that i updated it to latest release and still dont work.. now they say i have to edit some delay and i canot find where i edit it :\

**Comment by adskimomo** [comment]
if you use 2fa try https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/57 and create an app password
