### ISSUE TITLE
Eh?

### ISSUE THREAD

**Issue by phr34k0** [FeroxRev/Pokemon-Go-Rocket-API#71]
So where do i chunk this Put RefreshToken in settings for direct login .. 
does it go like = "023847982347" 
or
public  string GoogleRefreshToken { get; set; } = string.3945789347583745; ?

**Comment by jshield** [comment]
the former is a correct.

**Comment by FeroxRev** [comment]
if you wait 10 minutes it goes automatically ;)

**Comment by phr34k0** [comment]
Is cos i had to like restart everytime bag is full or a need to transfer. Its bit tedious
