### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by alex3604** [FeroxRev/Pokemon-Go-Rocket-API#72]
"Generated exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException'. from Pokemon Go Rocket API
Got an exception, trying automatic restart.."
And continue everytime to log me out anr re-log in continuosly everytime with the same error, why ? You know what is the problem ?
![cattura](https://cloud.githubusercontent.com/assets/11358999/17242761/40a9b89c-5579-11e6-8786-3fd024fe9b96.PNG)

**Comment by FeroxRev** [comment]
Not api related
