### ISSUE TITLE
Problems with PTC Login?

### ISSUE THREAD

**Issue by spikeone83** [FeroxRev/Pokemon-Go-Rocket-API#72]
Seems like loginResp.Headers.Location is always null so ticketId is not a value

using latest commit

**Comment by AlginMaduro** [comment]
probably PTC is down again...

**Comment by spikeone83** [comment]
loginResp status code is 200 (OK), didn't think server down returned this code

thanks

**Comment by FeroxRev** [comment]
I can log in just fine via PTC. Got latest commits?

**Comment by spikeone83** [comment]
just saw new commits, thanks Ferox
