### ISSUE TITLE
Stuck on await client.GetSettings()

### ISSUE THREAD

**Issue by zaitsevyan** [FeroxRev/Pokemon-Go-Rocket-API#74]
Hi, I am tring to run this project under mono on mac os. It stucks on var settings = await client.GetSettings();
I tried to skip this call but it stucks on GetMapObjects ...
after some time http task are cancelled by system (probably).

p.s. ptc login used

**Comment by FeroxRev** [comment]
Try google please

**Comment by TFMvdBroek** [comment]
Same happens to me with newest version (Google login)

**Comment by zaitsevyan** [comment]
I tried google login, but result is same :(

**Comment by jshield** [comment]
maybe a bug in the protobuf library or in mono?

**Comment by TFMvdBroek** [comment]
Logging just shows:

17:51:40 requesting GetPlayerResponse
17:51:40 requesting DownloadSettingsResponse
17:51:40 requesting GetMapObjectsResponse
17:51:40 requesting GetInventoryResponse
17:51:41 requesting GetMapObjectsResponse

and there it's stuck

**Comment by justh1n10** [comment]
I guess it happens to all of us. I'm getting the same.

**Comment by AlexStorm1313** [comment]
You don't need to change startup project. this will fix it

**Comment by FeroxRev** [comment]
Non issue?

**Comment by zaitsevyan** [comment]
@FeroxRev I found problem - it is http client keep-alive session. It stucks on SECOND request. I don't know how to solve this properly. I modify code to generate new httpclient-per-request and it is working now.

**Comment by FeroxRev** [comment]
I'm guessing this is related to mono. Sorry, no mono support from my side
