### ISSUE TITLE
API stuck on public static async Task<TResponsePayload> PostProtoPayload

### ISSUE THREAD

**Issue by fly2sky001** [FeroxRev/Pokemon-Go-Rocket-API#77]
Requesting FortSearchResponse
The thread 0xdb8 has exited with code 0 (0x0).
The thread 0x2770 has exited with code 0 (0x0).
The thread 0x6fc has exited with code 0 (0x0).

**Comment by JAL9302** [comment]
I am seeing the same in various APIs such as UpdatePlayerLocation and SetServer

**Comment by JAL9302** [comment]
Eventually get the exception "A task was canceled" after awhile.

**Comment by JAL9302** [comment]
Disregard, I resolved my issue by changing PokemonClient.cs to use ModernHttpClient like so
`
private static readonly HttpClientHandler Handler = new NativeMessageHandler
        {
            AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate,
            AllowAutoRedirect = false
        };
`

I think my issue was only because I was using this repo in a Xamarin app.

**Comment by ghost** [comment]
@jodoglevy I've found the ModnernHTTPClient project from Xamarin and downloaded it. May you can explain how you integrated it into the existing project?

You would help me alot. I try to get it working (even with other solutions) till saturday!

Best regards!

**Comment by JAL9302** [comment]
Already mentioned above. Search for `private static readonly HttpClientHandler Handler = new` and change `RetryHandler` to `NativeMessageHandler` at that spot.
