### ISSUE TITLE
Pokemons from Lured Pokestops

### ISSUE THREAD

**Issue by DaniilSokolyuk** [FeroxRev/Pokemon-Go-Rocket-API#78]
How to get pokemons spawned by lured pokestops? 
WildPokemons CatchablePokemons NearbyPokemons not works :(

**Comment by davidmann4** [comment]
#36

**Comment by MonsterMMORPG** [comment]
@DaniilSokolyuk did you manage to farm nearby pokemon? catchable pokemon?

i want to farm those Rather

**Comment by FeroxRev** [comment]
#36
