### ISSUE TITLE
using DankMemes.GPSOAuthSharp; unresolved import

### ISSUE THREAD

**Issue by pounard** [FeroxRev/Pokemon-Go-Rocket-API#78]
Since yesterday, when I did pull the latest modifications, the library is unable to compile because of this missing import.

Weird thing is that the dll has been download by monodevelop with the correct version.

**Comment by vmcall** [comment]
Manually add the library as a reference

**Comment by pounard** [comment]
Indeed, that did work, I had to manually select the asssembly dll my monodevelop wasn't finding it for an obscure reason. Thanks.
