### ISSUE TITLE
ITEM_TYPE_POTION -> GreatBall

### ISSUE THREAD

**Issue by thetemplar** [FeroxRev/Pokemon-Go-Rocket-API#79]
Shouldnt be the ITEM_TYPE_POTION in AllEnums.cs be the GreatBall? (And Revive the Ultra and so on)

**Comment by joshk6656** [comment]
also potions are not assigned an item type, just their id.

{  
         "modifiedTimestampMs":"1469030311604",
         "inventoryItemData":{  
            "item":{  
               "item":101,
               "count":5
            }
         }
      },
      {  
         "modifiedTimestampMs":"1469030353329",
         "inventoryItemData":{  
            "item":{  
               "item":102,
               "count":68
            }
         }
      },

**Comment by FeroxRev** [comment]
Are the values of the enums really moved by 1?

**Comment by joshk6656** [comment]
Normal pokeball right

**Comment by joshk6656** [comment]
I believe that it is looking at item type instead of item ID

**Comment by FeroxRev** [comment]
Cast it to a ItemId
