### ISSUE TITLE
The type or namespace name 'POGOProtos' could not be found

### ISSUE THREAD

**Issue by intsrc** [FeroxRev/Pokemon-Go-Rocket-API#79]
I'm getting the following message `The type or namespace name 'POGOProtos' could not be found`.
As i saw from config, this lib mus be in found in packages folder, but solution has no packages folder..

**Comment by pounard** [comment]
I guess you could experience a problem such as this #78

**Comment by FeroxRev** [comment]
Save the solution (only opening the project wont suffice) and then hit rebuild should restore the NuGet package
