### ISSUE TITLE
[Future Request] XP per Hour output

### ISSUE THREAD

**Issue by Spegeli** [FeroxRev/Pokemon-Go-Rocket-API#80]
I think most of us are interested in how many XP they get per hour.
Would be nice to get a XP per Hour output (every 5-15 Minutes).

Maybe together with a Pokemon catched per Hour

**Comment by Novalys** [comment]
I wrote a simple one, let me create the pull request.

**Comment by FeroxRev** [comment]
Closing as Novalys will PR something, cheers
