### ISSUE TITLE
WildPokemon always empty in get map objects

### ISSUE THREAD

**Issue by JAL9302** [FeroxRev/Pokemon-Go-Rocket-API#82]
From my previous playing with the API, there was always a WildPokemon object returned for each NearbyPokemon object that was returned, via the GetMapObjects API. However, using this library, I see no WildPokemon objects ever returned. I haven't sniffed the API since Niantic's update yesterday -- maybe they removed the WildPokemon objects?

**Comment by FeroxRev** [comment]
Niantic disabled it
