### ISSUE TITLE
PTC Login after commit c8f15ac not working

### ISSUE THREAD

**Issue by skupfer** [FeroxRev/Pokemon-Go-Rocket-API#82]
hi there,

trying to understand and figure out your code. After commit c8f15ac I am not able to login using PTC. I tried changing settings in either Settings.cs (like before) and App.config (under Rocket.API.Console, changed AuthType value to "Ptc"). Its always trying to login via google (message: go to google/device ...)

**Comment by FineNerds** [comment]
Same here. Even after forcing it to use PTC, it now has a bunch of nullexceptions

**Comment by skupfer** [comment]
Despite the fact that the servers are down/unstable again, I think we have to figure it out on our own. Seems like nobody wants to help. I am going back to this commit again trying to follow the code and changes.

If you are able to find a solution before I do I would be happy if you share it here :)

**Comment by FineNerds** [comment]
You can just remove the google login portion, forcing it to sign in with PTC, but then you get a bunch of errors with connecting to the servers through PTC. It seems like PTC support has been removed inadvertently

**Comment by skupfer** [comment]
I doubt he removed PTC support at all. There are alot of references to the server and so on... We are just doing something wrong I think.

**Comment by FineNerds** [comment]
Honestly I think it might just be servers down.
