### ISSUE TITLE
banned after update

### ISSUE THREAD

**Issue by davidmateos94** [FeroxRev/Pokemon-Go-Rocket-API#83]
so console crashed after 35 minutes, then I updated for the new commits and run it but seems like im banned now, i used the same location

12:51:13 requesting GetPlayerResponse
12:51:13 requesting DownloadSettingsResponse
12:51:14 requesting GetMapObjectsResponse
12:51:14 requesting GetInventoryResponse
12:51:14 requesting GetMapObjectsResponse
12:51:14 requesting PlayerUpdateResponse
12:51:14 requesting FortDetailsResponse
12:51:15 requesting FortSearchResponse
[12:51:15] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:51:30 requesting GetMapObjectsResponse
12:51:30 requesting PlayerUpdateResponse
12:51:30 requesting FortDetailsResponse
12:51:30 requesting FortSearchResponse
[12:51:31] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:51:46 requesting GetMapObjectsResponse
12:51:46 requesting PlayerUpdateResponse
12:51:46 requesting FortDetailsResponse
12:51:46 requesting FortSearchResponse
[12:51:46] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:52:01 requesting GetMapObjectsResponse
12:52:02 requesting PlayerUpdateResponse
12:52:02 requesting EncounterResponse
12:52:02 requesting CatchPokemonResponse
[12:52:02] Pidgey got away..
12:52:07 requesting PlayerUpdateResponse
12:52:07 requesting FortDetailsResponse
12:52:08 requesting FortSearchResponse
[12:52:08] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:52:23 requesting GetMapObjectsResponse
12:52:23 requesting PlayerUpdateResponse
12:52:23 requesting FortDetailsResponse
12:52:23 requesting FortSearchResponse
[12:52:24] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:52:39 requesting GetMapObjectsResponse
12:52:39 requesting PlayerUpdateResponse
12:52:39 requesting EncounterResponse
12:52:39 requesting CatchPokemonResponse
[12:52:39] Pidgeotto got away..
12:52:44 requesting PlayerUpdateResponse
12:52:45 requesting EncounterResponse
12:52:45 requesting CatchPokemonResponse
[12:52:45] Drowzee got away..
12:52:50 requesting PlayerUpdateResponse
12:52:50 requesting EncounterResponse
12:52:50 requesting CatchPokemonResponse
[12:52:51] Caterpie got away..
12:52:56 requesting PlayerUpdateResponse
12:52:56 requesting FortDetailsResponse
12:52:56 requesting FortSearchResponse
[12:52:56] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:53:11 requesting GetMapObjectsResponse
12:53:11 requesting PlayerUpdateResponse
12:53:12 requesting FortDetailsResponse
12:53:12 requesting FortSearchResponse
[12:53:12] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:53:27 requesting GetMapObjectsResponse
12:53:27 requesting PlayerUpdateResponse
12:53:27 requesting FortDetailsResponse
12:53:27 requesting FortSearchResponse
[12:53:28] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:53:43 requesting GetMapObjectsResponse
12:53:43 requesting PlayerUpdateResponse
12:53:43 requesting FortDetailsResponse
12:53:43 requesting FortSearchResponse
[12:53:43] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:53:58 requesting GetMapObjectsResponse
12:53:59 requesting PlayerUpdateResponse
12:53:59 requesting FortDetailsResponse
12:53:59 requesting FortSearchResponse
[12:53:59] Farmed XP: 0, Gems: 0, Eggs:  Items:
12:54:14 requesting GetMapObjectsResponse
12:54:14 requesting PlayerUpdateResponse
12:54:15 requesting EncounterResponse
12:54:15 requesting CatchPokemonResponse
[12:54:15] Spearow got away..
12:54:20 requesting PlayerUpdateResponse
12:54:20 requesting FortDetailsResponse
12:54:20 requesting FortSearchResponse
[12:54:21] Farmed XP: 0, Gems: 0, Eggs:  Items:

**Comment by muyochy** [comment]
you forgive put the location in the new update?

**Comment by fusspawn** [comment]
Your not banned. It just freaks out if your to far from the last sent location. (Ie you just teleported a huge amount of distance in way to short a time)  It just never gives xp and all pokemon escape.

**Comment by 0dinson** [comment]
Why are you not just running the game on your device like normal players and check yourself, instead of making crazy things up because the bot is not working..

**Comment by joshk6656** [comment]
Or you are out of normal pokeballs, its not smart enough to switch yet.

**Comment by FeroxRev** [comment]
Not an issue as sanity checks are most likely missing
