### ISSUE TITLE
Please let me know if current merged transfer/evolve pokemon work

### ISSUE THREAD

**Issue by FeroxRev** [FeroxRev/Pokemon-Go-Rocket-API#85]
Have to leave for next 3 hours, let me know whether all those 4 merges are still working :)

**Comment by Gh0stPanda** [comment]
Transfer works

**Comment by grimd34th** [comment]
:+1:

**Comment by SawyerHood** [comment]
Seems that TransferAllButStringestUnwantedPokemon() works. I'll check for certain when it is finished.

**Comment by pkiers** [comment]
The evolve works but have to change type from Pokemon to PokemonData and Type to Id.

**Comment by darkoulis12** [comment]
not working for me,

**Comment by Gh0stPanda** [comment]
The evolve works but the way its written in not optimal if you give your full list of Pokemon and should be rewritten with skipping the types that have already given a response with 3(Not enough candy) or 4(Type cannot evolve). 4 can also be avoided by making a list of all Pokemon that cannot evolve and check if the Pokemon is of that type.

**Comment by mich3lam** [comment]
@pkiers where do i choose what kind of pokemon to evolve?

**Comment by Gh0stPanda** [comment]
@mich3lam easiest way is to call the task in the execute method (I put it above "ExecuteFarmingPokestopsAndPokemons") with as parameters client and pokemons (it's filled there)

**Comment by FeroxRev** [comment]
Ok i guess these are working and that @darkoulis12 had server problems

**Comment by martin-podlubny** [comment]
Still unsure about evolve... Having real bad server issues atm, can't test.

**Comment by martin-podlubny** [comment]
So `Client.EvolvePokemon(ulong pokemonId)` does send the right request and properly evolves a pokemon if one has enough candy, but the returned `EvolvePokemonOutProto` object is bullshit. 

It's always SUCCESS and `ExpAwarded` and `CandyAwarded` are always zero. My guess is that it's a mismatch in proto definition that results in "garbage" :(

**Comment by martin-podlubny** [comment]
@FeroxRev any thoughts? :)

**Comment by FeroxRev** [comment]
Can you verify it by dumping the response with charles and comparing it with the proto? Cheers
