### ISSUE TITLE
[request] Add "bool hitPokemon = true" parameter

### ISSUE THREAD

**Issue by ghost** [FeroxRev/Pokemon-Go-Rocket-API#86]
Please add a parameter "bool hitPokemon = true" to CatchPokemon function in Encounter.cs allowing us to sometimes not catch the pokemons.

Also if you could give any hint about normalizedRecticleSize, spinModifier and normalizedHitPos parameters, it would be lovely (L)

BR,
John

**Comment by FeroxRev** [comment]
Sure, create a pull request :)
