### ISSUE TITLE
evolve

### ISSUE THREAD

**Issue by mich3lam** [FeroxRev/Pokemon-Go-Rocket-API#86]
at what file do i tell it what to evolve ?

**Comment by HelloKitty** [comment]
I couldn't find a protobuf definition for the request in this or other projects. Though, I wouldn't recommend implementing it.

I'm currently implementing auto-release for low CP Pokemon. I don't see how botting evolves would be beneficial though. Unless you're rebuilding the entire app.

**Comment by HelloKitty** [comment]
Actually, it was recently added. https://github.com/FeroxRev/Pokemon-Go-Rocket-API/blob/master/PokemonGo/RocketAPI/Proto/Payloads.proto check last payload.

Did this project overhaul protobuf def structure overnight =o?

**Comment by FeroxRev** [comment]
@HelloKitty Yes
