### ISSUE TITLE
Google Login doesnt work 

### ISSUE THREAD

**Issue by DOLLA-S1GN** [FeroxRev/Pokemon-Go-Rocket-API#90]
Using a PTC Accounts is working, but when I am trying to use a Google Account I just get System.ArgumentNullException in mscorlib.dll. Happening in this line:
`await client.SetServer();`

Edit: Ofc I added the GoogleRefreshToken, but it isnt working at the point stated above.

**Comment by blackms** [comment]
ATM Servers are unstable.

**Comment by FineNerds** [comment]
Yea. Server's aren't reliable. Neither login is working for me. And servers are unavailable for many people right now.
