### ISSUE TITLE
 await EvolveAllGivenPokemons(client,....)

### ISSUE THREAD

**Issue by Artarex** [FeroxRev/Pokemon-Go-Rocket-API#91]
I am not sure how to use the 2nd parameter needed 
Anyone has an example? lets say i want to evolve pidgey with id = 16
I dont know how to use this:  IEnumerable<Pokemon> pokemonToEvolve)

**Comment by pkiers** [comment]
Change the method to this:
`        private static async Task EvolveAllGivenPokemons(Client client, IEnumerable<PokemonData> pokemonToEvolve)
        {
            foreach (var pokemon in pokemonToEvolve)
            {
                /*
                enum Holoholo.Rpc.Types.EvolvePokemonOutProto.Result {
	                UNSET = 0;
	                SUCCESS = 1;
	                FAILED_POKEMON_MISSING = 2;
	                FAILED_INSUFFICIENT_RESOURCES = 3;
	                FAILED_POKEMON_CANNOT_EVOLVE = 4;
	                FAILED_POKEMON_IS_DEPLOYED = 5;
                }
                }*/

                var countOfEvolvedUnits = 0;
                var xpCount = 0;

                EvolvePokemonOut evolvePokemonOutProto;
                do
                {
                    evolvePokemonOutProto = await client.EvolvePokemon((ulong)pokemon.Id); //todo: someone check whether this still works

                    if (evolvePokemonOutProto.Result == 1)
                    {
                        System.Console.WriteLine($"Evolved {pokemon.PokemonId} successfully for {evolvePokemonOutProto.ExpAwarded}xp");

                        countOfEvolvedUnits++;
                        xpCount += evolvePokemonOutProto.ExpAwarded;
                    }
                    else
                    {
                        var result = evolvePokemonOutProto.Result;

                        System.Console.WriteLine($"Failed to evolve {pokemon.PokemonId}. " +
                                                 $"EvolvePokemonOutProto.Result was {result}");

                        System.Console.WriteLine($"Due to above error, stopping evolving {pokemon.PokemonId}");
                    }
                }
                while (evolvePokemonOutProto.Result == 1);

                System.Console.WriteLine($"Evolved {countOfEvolvedUnits} pieces of {pokemon.PokemonId} for {xpCount}xp");

                await Task.Delay(3000);
            }
        }`

And then call with
`var pokemons = inventory.InventoryDelta.InventoryItems.Select(i => i.InventoryItemData?.Pokemon).Where(p => p != null && p?.PokemonId > 0);
await EvolveAllGivenPokemons(client, pokemons);`

**Comment by Artarex** [comment]
How would it look without changing the method? I want to understand how the standart way works. Thanks for the help :)

**Comment by HelloKitty** [comment]
With the provided API you'll need to us LINQ to filter out Pokemon without the id.

I'm assuming you mean the 64bit GUID? Not the PokemonID?

Then you'd need to do this pokemon.Where(p => p.Id == 16); However, Id isn't suppose to be a 32bit int. Afaik it should be a 64bit GUID. So, ulong or something. You may need to change protobuf def if the ID produced is 0.

**Comment by FeroxRev** [comment]
Seems resolved
