### ISSUE TITLE
Proper RPC_Calls explanation

### ISSUE THREAD

**Issue by UntilSunrise** [FeroxRev/Pokemon-Go-Rocket-API#92]
We should emulate the client api usage as close as the original app.

Here a link: https://www.reddit.com/r/pokemongodev/comments/4tn3lm/the_heartbeats/

**Comment by FeroxRev** [comment]
What would you suggest to change?

**Comment by sooth** [comment]
That was a great read; unfortunately this is well beyond my skill set to help contribute to. I'll just leave it at a "+1" for this idea because being as hard to find as possible is always a good idea.
