### ISSUE TITLE
Bot performance drastically decreased?

### ISSUE THREAD

**Issue by FineNerds** [FeroxRev/Pokemon-Go-Rocket-API#95]
Last night I was catching around 4 pokemon/minute and looting 5-6 pokestops/minute. After all of the recent updates in the last day. The same location is yielding about 0.4 pokemon/minute and 0.2 pokestops/minute and this is on the Santa Monica Pier.

**Comment by Spegeli** [comment]
And the next n00b how dont know that his depends currently all on the server which are very instabil...

**Comment by HelloKitty** [comment]
The bot just sends protobuf packets stuffed into HTTP POSTs. It's only ever going to be slow if the server decides to respond slowly.
