### ISSUE TITLE
Naming of Pokemon type

### ISSUE THREAD

**Issue by ArcticXWolf** [FeroxRev/Pokemon-Go-Rocket-API#96]
Of course, this is just a point of everyone's own opinion and I have no problem, if this does not get changed, but shouldn't we rename the pokemonId field in pokemondata to type, race, pokedexId or pokemonType? This would reflect its meaning way more and we also already have a field called id for the individual Pokemon.

I will change it myself, but first wanted to ask, whether you also want this and which naming you prefer.

**Comment by ArcticXWolf** [comment]
I would stick with pokemondata.type, for simplicity.

**Comment by HelloKitty** [comment]
I think this is a decent proposal. pokemon_id is confusing since there is both an ID that represents the Pokemon as well as a GUID that represents the Pokemon in field 1.

Not type alone though. Too close to Type in .Net.

**Comment by FeroxRev** [comment]
The variable naming is directly reversed out of the apk. We then auto-create the classes from the .proto files. Renaming them by hand would not allow us in the future easy auto-generating from new/updated .proto files. We then have to manually change the names again. So I don't think it's a good idea to change the names, so let's stick to the .proto definition naming conventions.

**Comment by ArcticXWolf** [comment]
Ah, did Not know this. :)
